const distritosBasura = [
  { distrito: "SAN JUAN DE LURIGANCHO", basuraPorDia: 747.31 },
  { distrito: "SAN MARTIN DE PORRES", basuraPorDia: 616.58 },
  { distrito: "ATE", basuraPorDia: 484.94 },
  { distrito: "CALLAO", basuraPorDia: 338.18 },
  { distrito: "VILLA MARIA DEL TRIUNFO", basuraPorDia: 318.63 },
  { distrito: "VILLA EL SALVADOR", basuraPorDia: 311.16 },
  { distrito: "LOS OLIVOS", basuraPorDia: 287.13 },
  { distrito: "CARABAYLLO", basuraPorDia: 284.24 },
  { distrito: "SANTIAGO DE SURCO", basuraPorDia: 273.01 },
  { distrito: "SAN JUAN DE MIRAFLORES", basuraPorDia: 270.21 },
  { distrito: "PUENTE PIEDRA", basuraPorDia: 255.55 },
  { distrito: "PUENTE PIEDRA  ", basuraPorDia: 250.53 },
  { distrito: "CHORRILLOS", basuraPorDia: 238.61 },
  { distrito: "VENTANILLA", basuraPorDia: 211.44 },
  { distrito: "VENTANILLA  ", basuraPorDia: 205.68 },
  { distrito: "TRUJILLO", basuraPorDia: 196.39 },
  { distrito: "LIMA", basuraPorDia: 184.15 },
  { distrito: "JULIACA", basuraPorDia: 169.74 },
  { distrito: "JULIACA   ", basuraPorDia: 168.42 },
  { distrito: "LURIGANCHO", basuraPorDia: 160.38 },
  { distrito: "EL AGUSTINO", basuraPorDia: 158.3 },
  { distrito: "SANTA ANITA", basuraPorDia: 138.79 },
  { distrito: "EL TAMBO", basuraPorDia: 134.79 },
  { distrito: "JOSE LEONARDO ORTIZ", basuraPorDia: 133.63 },
  { distrito: "CHICLAYO", basuraPorDia: 131.86 },
  { distrito: "PIURA", basuraPorDia: 126.07 },
  { distrito: "ICA", basuraPorDia: 125.46 },
  { distrito: "CHIMBOTE", basuraPorDia: 123.56 },
  { distrito: "SULLANA", basuraPorDia: 121.63 },
  { distrito: "RIMAC", basuraPorDia: 121.01 },
  { distrito: "CAJAMARCA", basuraPorDia: 114.48 },
  { distrito: "CASTILLA", basuraPorDia: 112.74 },
  { distrito: "LA MOLINA", basuraPorDia: 112.21 },
  { distrito: "VEINTISEIS DE OCTUBRE", basuraPorDia: 108.43 },
  { distrito: "CALLERIA", basuraPorDia: 106.74 },
  { distrito: "VEINTISEIS DE OCTUBRE ", basuraPorDia: 105.93 },
  { distrito: "NUEVO CHIMBOTE", basuraPorDia: 105.32 },
  { distrito: "IQUITOS", basuraPorDia: 95.55 },
  { distrito: "IQUITOS  ", basuraPorDia: 95.38 },
  { distrito: "CERRO COLORADO", basuraPorDia: 89.18 },
  { distrito: "PACHACAMAC", basuraPorDia: 88.83 },
  { distrito: "PUNO", basuraPorDia: 88.43 },
  { distrito: "CERRO COLORADO ", basuraPorDia: 86.95 },
  { distrito: "SAN SEBASTIAN", basuraPorDia: 79.3 },
  { distrito: "PAUCARPATA", basuraPorDia: 78.12 },
  { distrito: "MANANTAY", basuraPorDia: 76.34 },
  { distrito: "BREÑA", basuraPorDia: 76.15 },
  { distrito: "YURIMAGUAS", basuraPorDia: 67.98 },
  { distrito: "JESUS MARIA", basuraPorDia: 67.12 },
  { distrito: "SAN BORJA", basuraPorDia: 66.75 },
  { distrito: "TAMBOPATA", basuraPorDia: 66.53 },
  { distrito: "PUEBLO LIBRE ", basuraPorDia: 66.35 },
  { distrito: "MAGDALENA VIEJA", basuraPorDia: 65.15 },
  { distrito: "LA VICTORIA", basuraPorDia: 64.56 },
  { distrito: "YARINACOCHA", basuraPorDia: 64.5 },
  { distrito: "HUANCAYO", basuraPorDia: 63.11 },
  { distrito: "ANCON", basuraPorDia: 62.21 },
  { distrito: "TUMBES", basuraPorDia: 62.16 },
  { distrito: "HUARAL", basuraPorDia: 61.78 },
  { distrito: "TACNA", basuraPorDia: 59.91 },
  { distrito: "TACNA   ", basuraPorDia: 59.48 },
  { distrito: "LURIN", basuraPorDia: 59.43 },
  { distrito: "AYACUCHO", basuraPorDia: 58.92 },
  { distrito: "AYACUCHO   ", basuraPorDia: 58.14 },
  { distrito: "HUANUCO", basuraPorDia: 56.73 },
  { distrito: "ANCON  ", basuraPorDia: 56.61 },
  { distrito: "SANTIAGO", basuraPorDia: 55.82 },
  { distrito: "TARAPOTO", basuraPorDia: 55.47 },
  { distrito: "VICTOR LARCO HERRERA", basuraPorDia: 54.6 },
  { distrito: "PARIÑAS", basuraPorDia: 54.31 },
  { distrito: "AMARILIS", basuraPorDia: 53.93 },
  { distrito: "HUANCHACO", basuraPorDia: 53.79 },
  { distrito: "HUACHO", basuraPorDia: 53.6 },
  { distrito: "CUSCO", basuraPorDia: 53.09 },
  { distrito: "CRNEL.GREGORIO ALBARRACIN LANCHIPA", basuraPorDia: 52.02 },
  { distrito: "LA PERLA", basuraPorDia: 51.69 },
  { distrito: "JAEN", basuraPorDia: 51.4 },
  { distrito: "CAYMA", basuraPorDia: 48.73 },
  { distrito: "PISCO", basuraPorDia: 48.73 },
  { distrito: "CHILCA", basuraPorDia: 48.16 },
  { distrito: "SURQUILLO", basuraPorDia: 48.14 },
  { distrito: "CORONEL GREGORIO ALBARRACIN LANCHIPA", basuraPorDia: 47.83 },
  { distrito: "AMARILIS ", basuraPorDia: 47.17 },
  { distrito: "PUNCHANA", basuraPorDia: 47.15 },
  { distrito: "INDEPENDENCIA", basuraPorDia: 46.73 },
  { distrito: "CHINCHA ALTA", basuraPorDia: 45.54 },
  { distrito: "MOYOBAMBA", basuraPorDia: 44.46 },
  { distrito: "MAGDALENA DEL MAR", basuraPorDia: 44.04 },
  { distrito: "HUARAZ", basuraPorDia: 43.9 },
  { distrito: "CATACAOS", basuraPorDia: 43.66 },
  { distrito: "PAITA", basuraPorDia: 42.77 },
  { distrito: "SOCABAYA", basuraPorDia: 42.54 },
  { distrito: "CHULUCANAS", basuraPorDia: 42.49 },
  { distrito: "ALTO SELVA ALEGRE", basuraPorDia: 42.21 },
  { distrito: "ILO", basuraPorDia: 38.5 },
  { distrito: "SAN MIGUEL   ", basuraPorDia: 38.15 },
  { distrito: "JOSE LUIS BUSTAMANTE Y RIVERO", basuraPorDia: 37.71 },
  { distrito: "CARMEN DE LA LEGUA REYNOSO", basuraPorDia: 37.66 },
  { distrito: "LAMBAYEQUE", basuraPorDia: 36.9 },
  { distrito: "ABANCAY", basuraPorDia: 36.71 },
  { distrito: "BARRANCA", basuraPorDia: 36.35 },
  { distrito: "PARCONA", basuraPorDia: 35.98 },
  { distrito: "MIRAFLORES", basuraPorDia: 33.83 },
  { distrito: "MARIANO MELGAR", basuraPorDia: 33.51 },
  { distrito: "MAJES", basuraPorDia: 33.0 },
  { distrito: "CHACLACAYO", basuraPorDia: 32.92 },
  { distrito: "MORALES", basuraPorDia: 32.83 },
  { distrito: "RUPA-RUPA   ", basuraPorDia: 32.23 },
  { distrito: "LINCE", basuraPorDia: 32.08 },
  { distrito: "RUPA-RUPA", basuraPorDia: 32.02 },
  { distrito: "SECHURA", basuraPorDia: 31.64 },
  { distrito: "HUAMACHUCO", basuraPorDia: 31.44 },
  { distrito: "LA BANDA DE SHILCAYO", basuraPorDia: 30.79 },
  { distrito: "TARMA", basuraPorDia: 30.35 },
  { distrito: "CIENEGUILLA", basuraPorDia: 29.94 },
  { distrito: "AREQUIPA", basuraPorDia: 29.37 },
  { distrito: "SAN JUAN BAUTISTA", basuraPorDia: 28.53 },
  { distrito: "PIMENTEL", basuraPorDia: 28.34 },
  { distrito: "CHEPEN", basuraPorDia: 27.86 },
  { distrito: "SUNAMPE", basuraPorDia: 27.06 },
  { distrito: "PILLCO MARCA  ", basuraPorDia: 26.88 },
  { distrito: "MOQUEGUA", basuraPorDia: 26.78 },
  { distrito: "PILLCO MARCA", basuraPorDia: 25.76 },
  { distrito: "JACOBO HUNTER", basuraPorDia: 25.69 },
  { distrito: "MI PERU", basuraPorDia: 25.16 },
  { distrito: "MI PERU  ", basuraPorDia: 24.64 },
  { distrito: "WANCHAQ", basuraPorDia: 24.59 },
  { distrito: "LA TINGUIÑA", basuraPorDia: 24.41 },
  { distrito: "SICUANI", basuraPorDia: 24.31 },
  { distrito: "TAMBO GRANDE", basuraPorDia: 23.95 },
  { distrito: "CASMA", basuraPorDia: 23.63 },
  { distrito: "HUANCAVELICA", basuraPorDia: 23.6 },
  { distrito: "VIRU", basuraPorDia: 23.57 },
  { distrito: "SAN VICENTE DE CAÑETE", basuraPorDia: 23.52 },
  { distrito: "NUEVA CAJAMARCA", basuraPorDia: 23.17 },
  { distrito: "CHAO", basuraPorDia: 23.16 },
  { distrito: "FERREÑAFE", basuraPorDia: 22.9 },
  { distrito: "HUAURA", basuraPorDia: 22.86 },
  { distrito: "PERENE", basuraPorDia: 22.6 },
  { distrito: "JUANJUI", basuraPorDia: 22.13 },
  { distrito: "BAGUA GRANDE", basuraPorDia: 22.09 },
  { distrito: "ANDAHUAYLAS", basuraPorDia: 21.97 },
  { distrito: "HUALMAY", basuraPorDia: 21.77 },
  { distrito: "YANAHUARA", basuraPorDia: 21.66 },
  { distrito: "HUANTA", basuraPorDia: 21.59 },
  { distrito: "IMPERIAL", basuraPorDia: 21.59 },
  { distrito: "SATIPO", basuraPorDia: 21.58 },
  { distrito: "CARMEN ALTO", basuraPorDia: 21.23 },
  { distrito: "HUANTA    ", basuraPorDia: 21.09 },
  { distrito: "CARMEN ALTO ", basuraPorDia: 20.95 },
  { distrito: "MOCHE", basuraPorDia: 20.13 },
  { distrito: "PACASMAYO", basuraPorDia: 19.87 },
  { distrito: "ANDRES AVELINO CACERES DORREGARAY", basuraPorDia: 19.82 },
  { distrito: "NASCA", basuraPorDia: 19.79 },
  { distrito: "FLORENCIA DE MORA", basuraPorDia: 19.7 },
  { distrito: "LA JOYA", basuraPorDia: 19.6 },
  { distrito: "ANDRES AVELINO CACERES DORREGARAY   ", basuraPorDia: 19.21 },
  { distrito: "ANDAHUAYLAS  ", basuraPorDia: 19.16 },
  { distrito: "SAN RAMON", basuraPorDia: 19.08 },
  { distrito: "SANTA MARIA", basuraPorDia: 18.35 },
  { distrito: "LAREDO", basuraPorDia: 18.15 },
  { distrito: "MARCAVELICA", basuraPorDia: 17.97 },
  { distrito: "SALAS", basuraPorDia: 17.94 },
  { distrito: "HUARMEY", basuraPorDia: 17.94 },
  { distrito: "YURA", basuraPorDia: 17.53 },
  { distrito: "ESPINAR", basuraPorDia: 17.43 },
  { distrito: "ZARUMILLA", basuraPorDia: 17.06 },
  { distrito: "BARRANCO", basuraPorDia: 16.77 },
  { distrito: "MOLLENDO", basuraPorDia: 16.77 },
  { distrito: "ALTO DE LA ALIANZA", basuraPorDia: 16.6 },
  { distrito: "SACHACA", basuraPorDia: 16.6 },
  { distrito: "REQUENA", basuraPorDia: 16.54 },
  { distrito: "CASA GRANDE", basuraPorDia: 16.53 },
  { distrito: "NASCA  ", basuraPorDia: 16.47 },
  { distrito: "CONTAMANA", basuraPorDia: 16.3 },
  { distrito: "GUADALUPE", basuraPorDia: 15.8 },
  { distrito: "RIOJA", basuraPorDia: 15.7 },
  { distrito: "PAIJAN", basuraPorDia: 15.55 },
  { distrito: "PATAPO", basuraPorDia: 15.38 },
  { distrito: "CHACHAPOYAS", basuraPorDia: 15.34 },
  { distrito: "MALA", basuraPorDia: 15.3 },
  { distrito: "GROCIO PRADO", basuraPorDia: 15.06 },
  { distrito: "SANTA ANA", basuraPorDia: 15.05 },
  { distrito: "MONSEFU", basuraPorDia: 15.04 },
  { distrito: "NAUTA", basuraPorDia: 14.97 },
  { distrito: "PADRE ABAD", basuraPorDia: 14.94 },
  { distrito: "BAGUA", basuraPorDia: 14.91 },
  { distrito: "PANGOA", basuraPorDia: 14.9 },
  { distrito: "SALAVERRY", basuraPorDia: 14.62 },
  { distrito: "PUNTA HERMOSA", basuraPorDia: 14.52 },
  { distrito: "TUMAN", basuraPorDia: 14.28 },
  { distrito: "CHANCHAMAYO", basuraPorDia: 14.24 },
  { distrito: "SUBTANJALLA", basuraPorDia: 14.14 },
  { distrito: "TOCACHE", basuraPorDia: 13.18 },
  { distrito: "AGUAS VERDES", basuraPorDia: 12.86 },
  { distrito: "QUERECOTILLO", basuraPorDia: 12.32 },
  { distrito: "VEGUETA", basuraPorDia: 12.24 },
  { distrito: "HUANCAN", basuraPorDia: 11.98 },
  { distrito: "CELENDIN", basuraPorDia: 11.96 },
  { distrito: "IGNACIO ESCUDERO", basuraPorDia: 11.87 },
  { distrito: "BAGUA ", basuraPorDia: 11.8 },
  { distrito: "PANGOA  ", basuraPorDia: 11.73 },
  { distrito: "JESUS NAZARENO", basuraPorDia: 11.66 },
  { distrito: "RAIMONDI", basuraPorDia: 11.49 },
  { distrito: "RAYMONDI", basuraPorDia: 11.49 },
  { distrito: "PICHARI", basuraPorDia: 11.46 },
  { distrito: "PICHANAQUI", basuraPorDia: 11.45 },
  { distrito: "URUBAMBA", basuraPorDia: 11.27 },
  { distrito: "LAS PIEDRAS", basuraPorDia: 11.17 },
  { distrito: "SUPE", basuraPorDia: 11.15 },
  { distrito: "SAN CLEMENTE", basuraPorDia: 10.98 },
  { distrito: "TUPAC AMARU INCA", basuraPorDia: 10.97 },
  { distrito: "PUCUSANA", basuraPorDia: 10.92 },
  { distrito: "BAMBAMARCA", basuraPorDia: 10.9 },
  { distrito: "JAUJA", basuraPorDia: 10.9 },
  { distrito: "PATIVILCA", basuraPorDia: 10.86 },
  { distrito: "POMALCA", basuraPorDia: 10.82 },
  { distrito: "COISHCO", basuraPorDia: 10.8 },
  { distrito: "CARAZ", basuraPorDia: 10.77 },
  { distrito: "LOS AQUIJES", basuraPorDia: 10.68 },
  { distrito: "SORITOR", basuraPorDia: 10.58 },
  { distrito: "JOSE CRESPO Y CASTILLO       ", basuraPorDia: 10.36 },
  { distrito: "CAJABAMBA", basuraPorDia: 10.32 },
  { distrito: "ETEN", basuraPorDia: 10.32 },
  { distrito: "SAMUEL PASTOR", basuraPorDia: 10.22 },
  { distrito: "JOSE CRESPO Y CASTILLO", basuraPorDia: 10.22 },
  { distrito: "LAS PIEDRAS  ", basuraPorDia: 10.08 },
  { distrito: "SAPALLANGA", basuraPorDia: 10.02 },
  { distrito: "PICSI", basuraPorDia: 10.0 },
  { distrito: "OLMOS", basuraPorDia: 9.87 },
  { distrito: "CALCA", basuraPorDia: 9.69 },
  { distrito: "POCOLLAY", basuraPorDia: 9.67 },
  { distrito: "CIUDAD NUEVA", basuraPorDia: 9.61 },
  { distrito: "LAMAS", basuraPorDia: 9.55 },
  { distrito: "CUTERVO", basuraPorDia: 9.5 },
  { distrito: "LOS BAÑOS DEL INCA", basuraPorDia: 9.48 },
  { distrito: "SAN ANDRES", basuraPorDia: 9.47 },
  { distrito: "LA ARENA", basuraPorDia: 9.42 },
  { distrito: "PARAMONGA", basuraPorDia: 9.2 },
  { distrito: "MAZAMARI", basuraPorDia: 9.19 },
  { distrito: "MAZAMARI ", basuraPorDia: 9.16 },
  { distrito: "CHONGOYAPE", basuraPorDia: 9.11 },
  { distrito: "RAMON CASTILLA", basuraPorDia: 9.05 },
  { distrito: "PACANGA", basuraPorDia: 8.96 },
  { distrito: "TIABAYA", basuraPorDia: 8.86 },
  { distrito: "ASCENSION", basuraPorDia: 8.82 },
  { distrito: "ILAVE", basuraPorDia: 8.8 },
  { distrito: "SUPE PUERTO", basuraPorDia: 8.69 },
  { distrito: "CHOTA", basuraPorDia: 8.59 },
  { distrito: "SAYAN", basuraPorDia: 8.52 },
  { distrito: "SANTA", basuraPorDia: 8.51 },
  { distrito: "CHAUPIMARCA", basuraPorDia: 8.46 },
  { distrito: "ELIAS SOPLIN VARGAS", basuraPorDia: 8.35 },
  { distrito: "SANTIAGO DE CAO", basuraPorDia: 8.16 },
  { distrito: "SAN AGUSTIN", basuraPorDia: 8.12 },
  { distrito: "AUCALLAMA", basuraPorDia: 7.88 },
  { distrito: "QUILMANA", basuraPorDia: 7.69 },
  { distrito: "AMBO", basuraPorDia: 7.65 },
  { distrito: "REQUE", basuraPorDia: 7.62 },
  { distrito: "ANANEA", basuraPorDia: 7.59 },
  { distrito: "LAS LOMAS", basuraPorDia: 7.47 },
  { distrito: "PILCOMAYO", basuraPorDia: 7.43 },
  { distrito: "CHUPACA", basuraPorDia: 7.42 },
  { distrito: "MANCORA", basuraPorDia: 7.34 },
  { distrito: "CONSTITUCION", basuraPorDia: 7.29 },
  { distrito: "LOS ORGANOS", basuraPorDia: 7.21 },
  { distrito: "CAMANA", basuraPorDia: 7.18 },
  { distrito: "ZORRITOS", basuraPorDia: 7.17 },
  { distrito: "SAPOSOA", basuraPorDia: 7.17 },
  { distrito: "CONSTITUCION ", basuraPorDia: 7.15 },
  { distrito: "SAN IGNACIO", basuraPorDia: 7.14 },
  { distrito: "MORROPON", basuraPorDia: 7.06 },
  { distrito: "SANTA EULALIA", basuraPorDia: 7.02 },
  { distrito: "PICOTA", basuraPorDia: 6.99 },
  { distrito: "VILLA RICA", basuraPorDia: 6.94 },
  { distrito: "UCHUMAYO", basuraPorDia: 6.92 },
  { distrito: "LA OROYA", basuraPorDia: 6.91 },
  { distrito: "SAN JOSE DE SISA", basuraPorDia: 6.78 },
  { distrito: "OTUZCO", basuraPorDia: 6.71 },
  { distrito: "PUQUIO", basuraPorDia: 6.66 },
  { distrito: "SAMEGUA", basuraPorDia: 6.62 },
  { distrito: "MIGUEL CHECA", basuraPorDia: 6.47 },
  { distrito: "INAMBARI", basuraPorDia: 6.45 },
  { distrito: "CHARACATO", basuraPorDia: 6.44 },
  { distrito: "LA HUACA", basuraPorDia: 6.37 },
  { distrito: "CHICAMA", basuraPorDia: 6.29 },
  { distrito: "CAYALTI", basuraPorDia: 6.29 },
  { distrito: "NEPEÑA", basuraPorDia: 6.16 },
  { distrito: "SAN JERONIMO DE TUNAN", basuraPorDia: 6.14 },
  { distrito: "PARDO MIGUEL", basuraPorDia: 6.13 },
  { distrito: "INAMBARI   ", basuraPorDia: 6.03 },
  { distrito: "CASTILLO GRANDE", basuraPorDia: 5.77 },
  { distrito: "CASTILLO GRANDE   ", basuraPorDia: 5.76 },
  { distrito: "LA BREA", basuraPorDia: 5.74 },
  { distrito: "JAYANCA", basuraPorDia: 5.73 },
  { distrito: "SAÑA", basuraPorDia: 5.68 },
  { distrito: "LIRCAY", basuraPorDia: 5.68 },
  { distrito: "SAN JOSE", basuraPorDia: 5.67 },
  { distrito: "NUEVO IMPERIAL", basuraPorDia: 5.65 },
  { distrito: "LA MATANZA", basuraPorDia: 5.65 },
  { distrito: "YAUYOS", basuraPorDia: 5.59 },
  { distrito: "POROY", basuraPorDia: 5.57 },
  { distrito: "MARCONA", basuraPorDia: 5.55 },
  { distrito: "DEAN VALDIVIA", basuraPorDia: 5.54 },
  { distrito: "QUIRUVILCA", basuraPorDia: 5.52 },
  { distrito: "MORROPE", basuraPorDia: 5.52 },
  { distrito: "LA CRUZ", basuraPorDia: 5.4 },
  { distrito: "VICE", basuraPorDia: 5.4 },
  { distrito: "UCHIZA", basuraPorDia: 5.33 },
  { distrito: "TAMBURCO", basuraPorDia: 5.31 },
  { distrito: "CHALLHUAHUACHO", basuraPorDia: 5.25 },
  { distrito: "ORCOPAMPA", basuraPorDia: 5.25 },
  { distrito: "TALAVERA", basuraPorDia: 5.23 },
  { distrito: "OXAPAMPA", basuraPorDia: 5.22 },
  { distrito: "ASIA", basuraPorDia: 5.18 },
  { distrito: "PEDRO GALVEZ", basuraPorDia: 5.08 },
  { distrito: "CORRALES", basuraPorDia: 5.01 },
  { distrito: "CORACORA", basuraPorDia: 4.92 },
  { distrito: "COLAN", basuraPorDia: 4.92 },
  { distrito: "SAN PEDRO DE LLOC", basuraPorDia: 4.83 },
  { distrito: "DESAGUADERO", basuraPorDia: 4.83 },
  { distrito: "KIMBIRI", basuraPorDia: 4.82 },
  { distrito: "PARACAS", basuraPorDia: 4.81 },
  { distrito: "SAN BARTOLO", basuraPorDia: 4.79 },
  { distrito: "PUCALA", basuraPorDia: 4.79 },
  { distrito: "SICAYA", basuraPorDia: 4.76 },
  { distrito: "CHINCHA BAJA", basuraPorDia: 4.75 },
  { distrito: "PAMPAS  ", basuraPorDia: 4.74 },
  { distrito: "LAGUNAS", basuraPorDia: 4.73 },
  { distrito: "CHALA", basuraPorDia: 4.7 },
  { distrito: "EL ALTO", basuraPorDia: 4.69 },
  { distrito: "RICARDO PALMA", basuraPorDia: 4.67 },
  { distrito: "PARCOY", basuraPorDia: 4.67 },
  { distrito: "CURA MORI", basuraPorDia: 4.61 },
  { distrito: "CHIVAY", basuraPorDia: 4.56 },
  { distrito: "ANCO-HUALLO", basuraPorDia: 4.52 },
  { distrito: "PUNTA NEGRA", basuraPorDia: 4.49 },
  { distrito: "MACUSANI", basuraPorDia: 4.47 },
  { distrito: "TABALOSOS", basuraPorDia: 4.46 },
  { distrito: "HUAMANCACA CHICO", basuraPorDia: 4.36 },
  { distrito: "SANTA RITA DE SIGUAS", basuraPorDia: 4.35 },
  { distrito: "AYNA", basuraPorDia: 4.23 },
  { distrito: "PUTINA", basuraPorDia: 4.17 },
  { distrito: "IRAZOLA", basuraPorDia: 4.15 },
  { distrito: "CAMPOVERDE", basuraPorDia: 4.12 },
  { distrito: "SANTIAGO DE CHUCO", basuraPorDia: 4.09 },
  { distrito: "CAJARURO ", basuraPorDia: 4.09 },
  { distrito: "PALPA", basuraPorDia: 4.09 },
  { distrito: "MOCHUMI", basuraPorDia: 4.08 },
  { distrito: "PITIPO", basuraPorDia: 4.04 },
  { distrito: "YUNGAY", basuraPorDia: 4.04 },
  { distrito: "IRAZOLA  ", basuraPorDia: 4.02 },
  { distrito: "YUNGUYO", basuraPorDia: 4.02 },
  { distrito: "CAJARURO", basuraPorDia: 3.98 },
  { distrito: "HUALLANCA", basuraPorDia: 3.93 },
  { distrito: "URCOS", basuraPorDia: 3.87 },
  { distrito: "CRUCERO", basuraPorDia: 3.85 },
  { distrito: "NICOLAS DE PIEROLA", basuraPorDia: 3.84 },
  { distrito: "CHOCOPE", basuraPorDia: 3.8 },
  { distrito: "MOTUPE", basuraPorDia: 3.77 },
  { distrito: "DANIEL HERNANDEZ  ", basuraPorDia: 3.77 },
  { distrito: "EL ALGARROBAL", basuraPorDia: 3.75 },
  { distrito: "DANIEL HERNANDEZ", basuraPorDia: 3.73 },
  { distrito: "OYON", basuraPorDia: 3.68 },
  { distrito: "CARHUAZ", basuraPorDia: 3.67 },
  { distrito: "SIMON BOLIVAR", basuraPorDia: 3.67 },
  { distrito: "HUARIACA", basuraPorDia: 3.67 },
  { distrito: "HUAYUCACHI", basuraPorDia: 3.62 },
  { distrito: "BUENOS AIRES", basuraPorDia: 3.6 },
  { distrito: "ALONSO DE ALVARADO", basuraPorDia: 3.58 },
  { distrito: "HUEPETUHE", basuraPorDia: 3.57 },
  { distrito: "RAZURI", basuraPorDia: 3.56 },
  { distrito: "YANAHUANCA", basuraPorDia: 3.54 },
  { distrito: "PACHACUTEC", basuraPorDia: 3.52 },
  { distrito: "POMABAMBA", basuraPorDia: 3.51 },
  { distrito: "LLATA", basuraPorDia: 3.47 },
  { distrito: "CHAZUTA", basuraPorDia: 3.46 },
  { distrito: "APLAO", basuraPorDia: 3.46 },
  { distrito: "TUCUME", basuraPorDia: 3.44 },
  { distrito: "CAYNARACHI", basuraPorDia: 3.43 },
  { distrito: "GUADALUPITO", basuraPorDia: 3.38 },
  { distrito: "CAYNARACHI   ", basuraPorDia: 3.37 },
  { distrito: "EL TALLAN", basuraPorDia: 3.33 },
  { distrito: "PUNTA DE BOMBON", basuraPorDia: 3.32 },
  { distrito: "TINYAHUARCO", basuraPorDia: 3.29 },
  { distrito: "SAN JACINTO", basuraPorDia: 3.27 },
  { distrito: "SANTA ROSA DE SACCO", basuraPorDia: 3.27 },
  { distrito: "PACHIZA", basuraPorDia: 3.26 },
  { distrito: "SAN JUAN DE LA VIRGEN", basuraPorDia: 3.22 },
  { distrito: "NESHUYA", basuraPorDia: 3.21 },
  { distrito: "ASCOPE", basuraPorDia: 3.2 },
  { distrito: "NESHUYA   ", basuraPorDia: 3.12 },
  { distrito: "TAMBO DE MORA", basuraPorDia: 3.1 },
  { distrito: "CURIMANA", basuraPorDia: 3.08 },
  { distrito: "MARISCAL CACERES", basuraPorDia: 3.07 },
  { distrito: "IMAZA", basuraPorDia: 3.06 },
  { distrito: "CURAHUASI", basuraPorDia: 3.06 },
  { distrito: "HUICUNGO", basuraPorDia: 3.04 },
  { distrito: "SALITRAL", basuraPorDia: 3.02 },
  { distrito: "CAMPANILLA", basuraPorDia: 3.02 },
  { distrito: "SAN JOSE DE LOS MOLINOS", basuraPorDia: 3.01 },
  { distrito: "QUEQUEÑA", basuraPorDia: 3.0 },
  { distrito: "LA UNION", basuraPorDia: 2.99 },
  { distrito: "JUNIN", basuraPorDia: 2.96 },
  { distrito: "HUAYLLAY", basuraPorDia: 2.95 },
  { distrito: "BERNAL", basuraPorDia: 2.94 },
  { distrito: "SARAYACU", basuraPorDia: 2.94 },
  { distrito: "FERNANDO LORES", basuraPorDia: 2.9 },
  { distrito: "COCACHACRA", basuraPorDia: 2.9 },
  { distrito: "ILABAYA", basuraPorDia: 2.89 },
  { distrito: "CAYLLOMA", basuraPorDia: 2.87 },
  { distrito: "OYOTUN", basuraPorDia: 2.84 },
  { distrito: "SAYLLA", basuraPorDia: 2.83 },
  { distrito: "CERRO AZUL", basuraPorDia: 2.8 },
  { distrito: "MONZON", basuraPorDia: 2.79 },
  { distrito: "MACHUPICCHU", basuraPorDia: 2.76 },
  { distrito: "LONYA GRANDE", basuraPorDia: 2.76 },
  { distrito: "HUMAY", basuraPorDia: 2.75 },
  { distrito: "JEPELACIO", basuraPorDia: 2.75 },
  { distrito: "LABERINTO", basuraPorDia: 2.74 },
  { distrito: "MORO", basuraPorDia: 2.74 },
  { distrito: "JULI", basuraPorDia: 2.71 },
  { distrito: "CALETA DE CARQUIN", basuraPorDia: 2.7 },
  { distrito: "MAZAN", basuraPorDia: 2.64 },
  { distrito: "ACARI", basuraPorDia: 2.61 },
  { distrito: "PUTUMAYO    ", basuraPorDia: 2.6 },
  { distrito: "ALEXANDER VON HUMBOLDT", basuraPorDia: 2.59 },
  { distrito: "MATAHUASI", basuraPorDia: 2.58 },
  { distrito: "PAPAYAL", basuraPorDia: 2.55 },
  { distrito: "ALEXANDER VON HUMBOLDT  ", basuraPorDia: 2.53 },
  { distrito: "ISLAY", basuraPorDia: 2.53 },
  { distrito: "NUEVO PROGRESO", basuraPorDia: 2.52 },
  { distrito: "SAUCE", basuraPorDia: 2.51 },
  { distrito: "SAN NICOLAS", basuraPorDia: 2.51 },
  { distrito: "CANOAS DE PUNTA SAL", basuraPorDia: 2.5 },
  { distrito: "OCONGATE", basuraPorDia: 2.46 },
  { distrito: "NIEVA ", basuraPorDia: 2.43 },
  { distrito: "CAMPORREDONDO", basuraPorDia: 2.42 },
  { distrito: "SAMUGARI", basuraPorDia: 2.41 },
  { distrito: "JEQUETEPEQUE", basuraPorDia: 2.4 },
  { distrito: "HUARANGO", basuraPorDia: 2.39 },
  { distrito: "LLOCHEGUA", basuraPorDia: 2.39 },
  { distrito: "PULLO", basuraPorDia: 2.38 },
  { distrito: "NIEVA", basuraPorDia: 2.38 },
  { distrito: "MOROCOCHA", basuraPorDia: 2.37 },
  { distrito: "SIHUAS", basuraPorDia: 2.36 },
  { distrito: "PISAC", basuraPorDia: 2.36 },
  { distrito: "VARGAS GUERRA", basuraPorDia: 2.34 },
  { distrito: "PUTUMAYO", basuraPorDia: 2.34 },
  { distrito: "ILLIMO", basuraPorDia: 2.34 },
  { distrito: "HUANCANE", basuraPorDia: 2.32 },
  { distrito: "SANTA ANA DE TUSI", basuraPorDia: 2.3 },
  { distrito: "CONCHUCOS", basuraPorDia: 2.29 },
  { distrito: "ACOBAMBA ", basuraPorDia: 2.29 },
  { distrito: "LA PUNTA", basuraPorDia: 2.28 },
  { distrito: "BELLAVISTA DE LA UNION", basuraPorDia: 2.28 },
  { distrito: "SIVIA", basuraPorDia: 2.28 },
  { distrito: "IBERIA", basuraPorDia: 2.28 },
  { distrito: "ALTO SAPOSOA", basuraPorDia: 2.27 },
  { distrito: "PUCARA", basuraPorDia: 2.27 },
  { distrito: "INDIANA", basuraPorDia: 2.26 },
  { distrito: "TAMBO", basuraPorDia: 2.25 },
  { distrito: "ECHARATE", basuraPorDia: 2.25 },
  { distrito: "HAQUIRA", basuraPorDia: 2.25 },
  { distrito: "LLOCHEGUA   ", basuraPorDia: 2.25 },
  { distrito: "LUYANDO", basuraPorDia: 2.23 },
  { distrito: "OCOÑA", basuraPorDia: 2.21 },
  { distrito: "YONAN", basuraPorDia: 2.21 },
  { distrito: "SIVIA   ", basuraPorDia: 2.21 },
  { distrito: "LUYANDO ", basuraPorDia: 2.2 },
  { distrito: "JUAN GUERRA", basuraPorDia: 2.2 },
  { distrito: "YAULI", basuraPorDia: 2.19 },
  { distrito: "MOLLEBAYA", basuraPorDia: 2.18 },
  { distrito: "POMACANCHI", basuraPorDia: 2.17 },
  { distrito: "OLLANTAYTAMBO", basuraPorDia: 2.16 },
  { distrito: "PACOCHA", basuraPorDia: 2.16 },
  { distrito: "ARAMANGO", basuraPorDia: 2.15 },
  { distrito: "ALTO BIAVO", basuraPorDia: 2.14 },
  { distrito: "BARRANQUITA", basuraPorDia: 2.14 },
  { distrito: "ANTAUTA", basuraPorDia: 2.14 },
  { distrito: "MARIANO DAMASO BERAUN", basuraPorDia: 2.12 },
  { distrito: "MASISEA", basuraPorDia: 2.11 },
  { distrito: "RIO NEGRO ", basuraPorDia: 2.11 },
  { distrito: "RIO NEGRO", basuraPorDia: 2.1 },
  { distrito: "ALTO LARAN", basuraPorDia: 2.09 },
  { distrito: "PUERTO INCA", basuraPorDia: 2.09 },
  { distrito: "CANOAS DE PUNTA SAL ", basuraPorDia: 2.04 },
  { distrito: "SEPAHUA", basuraPorDia: 2.03 },
  { distrito: "SAN JUAN DE BIGOTE", basuraPorDia: 2.02 },
  { distrito: "SANDIA", basuraPorDia: 2.02 },
  { distrito: "HUARI", basuraPorDia: 2.0 },
  { distrito: "VICHAYAL", basuraPorDia: 1.98 },
  { distrito: "ACOLLA", basuraPorDia: 1.98 },
  { distrito: "PAUCARTAMBO", basuraPorDia: 1.97 },
  { distrito: "PAMPAS DE HOSPITAL", basuraPorDia: 1.96 },
  { distrito: "MATAPALO", basuraPorDia: 1.95 },
  { distrito: "TATE", basuraPorDia: 1.95 },
  { distrito: "CHURCAMPA", basuraPorDia: 1.93 },
  { distrito: "SAUSA", basuraPorDia: 1.89 },
  { distrito: "PEBAS", basuraPorDia: 1.89 },
  { distrito: "CHALHUANCA", basuraPorDia: 1.88 },
  { distrito: "CASCAS", basuraPorDia: 1.88 },
  { distrito: "AWAJUN", basuraPorDia: 1.86 },
  { distrito: "SANTA MARIA DE CHICMO", basuraPorDia: 1.85 },
  { distrito: "CACATACHI", basuraPorDia: 1.85 },
  { distrito: "SABANDIA", basuraPorDia: 1.85 },
  { distrito: "HUASAHUASI", basuraPorDia: 1.84 },
  { distrito: "RIO TAMBO", basuraPorDia: 1.84 },
  { distrito: "SHAMBOYACU", basuraPorDia: 1.82 },
  { distrito: "BELLAVISTA", basuraPorDia: 1.82 },
  { distrito: "JOSE MARIA ARGUEDAS", basuraPorDia: 1.8 },
  { distrito: "PITUMARCA", basuraPorDia: 1.8 },
  { distrito: "PAIMAS", basuraPorDia: 1.8 },
  { distrito: "CALZADA", basuraPorDia: 1.79 },
  { distrito: "SAN MIGUEL", basuraPorDia: 1.78 },
  { distrito: "OCUCAJE", basuraPorDia: 1.78 },
  { distrito: "CUMBA", basuraPorDia: 1.77 },
  { distrito: "CHIRINOS", basuraPorDia: 1.77 },
  { distrito: "SAN MARTIN", basuraPorDia: 1.76 },
  { distrito: "LUNAHUANA", basuraPorDia: 1.73 },
  { distrito: "TENIENTE CESAR LOPEZ ROJAS", basuraPorDia: 1.72 },
  { distrito: "JOSE MARIA ARGUEDAS  ", basuraPorDia: 1.72 },
  { distrito: "TAYABAMBA", basuraPorDia: 1.71 },
  { distrito: "AYABACA", basuraPorDia: 1.71 },
  { distrito: "MAGDALENA DE CAO", basuraPorDia: 1.7 },
  { distrito: "MOLINO", basuraPorDia: 1.69 },
  { distrito: "AMOTAPE", basuraPorDia: 1.68 },
  { distrito: "SAN HILARION", basuraPorDia: 1.66 },
  { distrito: "SAN MARCOS", basuraPorDia: 1.66 },
  { distrito: "PANAO", basuraPorDia: 1.66 },
  { distrito: "SUYO", basuraPorDia: 1.65 },
  { distrito: "SAN PABLO", basuraPorDia: 1.63 },
  { distrito: "PACORA", basuraPorDia: 1.62 },
  { distrito: "URACA", basuraPorDia: 1.61 },
  { distrito: "QUIQUIJANA", basuraPorDia: 1.6 },
  { distrito: "PUERTO BERMUDEZ", basuraPorDia: 1.59 },
  { distrito: "TAHUANIA", basuraPorDia: 1.59 },
  { distrito: "MANSERICHE", basuraPorDia: 1.57 },
  { distrito: "HUARO", basuraPorDia: 1.57 },
  { distrito: "CANAYRE", basuraPorDia: 1.57 },
  { distrito: "RECUAY", basuraPorDia: 1.56 },
  { distrito: "BELLA UNION", basuraPorDia: 1.56 },
  { distrito: "CHONTABAMBA", basuraPorDia: 1.56 },
  { distrito: "HUACHON", basuraPorDia: 1.55 },
  { distrito: "CHUSCHI", basuraPorDia: 1.55 },
  { distrito: "TAMARINDO", basuraPorDia: 1.55 },
  { distrito: "RINCONADA LLICUAR", basuraPorDia: 1.55 },
  { distrito: "BOQUERON", basuraPorDia: 1.53 },
  { distrito: "USICAYOS", basuraPorDia: 1.53 },
  { distrito: "SAÑO", basuraPorDia: 1.52 },
  { distrito: "NUEVA REQUENA", basuraPorDia: 1.52 },
  { distrito: "MARCA", basuraPorDia: 1.52 },
  { distrito: "URARINAS", basuraPorDia: 1.51 },
  { distrito: "SAN JOSE DE LOURDES", basuraPorDia: 1.51 },
  { distrito: "TAHUAMANU", basuraPorDia: 1.5 },
  { distrito: "ANCAHUASI", basuraPorDia: 1.5 },
  { distrito: "URARINAS   ", basuraPorDia: 1.5 },
  { distrito: "COYA", basuraPorDia: 1.49 },
  { distrito: "CHAGLLA", basuraPorDia: 1.49 },
  { distrito: "USQUIL", basuraPorDia: 1.48 },
  { distrito: "CANAYRE  ", basuraPorDia: 1.48 },
  { distrito: "SAMA", basuraPorDia: 1.47 },
  { distrito: "PUCACACA", basuraPorDia: 1.47 },
  { distrito: "LA PECA ", basuraPorDia: 1.46 },
  { distrito: "EMILIO SAN MARTIN", basuraPorDia: 1.46 },
  { distrito: "TROMPETEROS", basuraPorDia: 1.46 },
  { distrito: "HUALHUAS", basuraPorDia: 1.46 },
  { distrito: "BAJO BIAVO", basuraPorDia: 1.46 },
  { distrito: "HUANCARAMA", basuraPorDia: 1.46 },
  { distrito: "ORCOTUNA", basuraPorDia: 1.46 },
  { distrito: "HUIPOCA", basuraPorDia: 1.45 },
  { distrito: "CARHUAMAYO", basuraPorDia: 1.45 },
  { distrito: "ASILLO", basuraPorDia: 1.44 },
  { distrito: "CRISTO NOS VALGA", basuraPorDia: 1.44 },
  { distrito: "ETEN PUERTO", basuraPorDia: 1.43 },
  { distrito: "LA PECA", basuraPorDia: 1.43 },
  { distrito: "PAUSA", basuraPorDia: 1.42 },
  { distrito: "AHUAC", basuraPorDia: 1.42 },
  { distrito: "SAMANCO", basuraPorDia: 1.42 },
  { distrito: "SAN MIGUEL DE EL FAIQUE", basuraPorDia: 1.42 },
  { distrito: "VIQUES", basuraPorDia: 1.41 },
  { distrito: "PAUCARA ", basuraPorDia: 1.41 },
  { distrito: "TACABAMBA", basuraPorDia: 1.4 },
  { distrito: "CHONGOS BAJO", basuraPorDia: 1.4 },
  { distrito: "MAQUIA", basuraPorDia: 1.4 },
  { distrito: "POLVORA", basuraPorDia: 1.39 },
  { distrito: "PATAZ", basuraPorDia: 1.39 },
  { distrito: "CHIQUIAN", basuraPorDia: 1.37 },
  { distrito: "SHAPAJA", basuraPorDia: 1.37 },
  { distrito: "LARES", basuraPorDia: 1.36 },
  { distrito: "LIMATAMBO", basuraPorDia: 1.36 },
  { distrito: "EL MILAGRO", basuraPorDia: 1.35 },
  { distrito: "BUENA VISTA ALTA", basuraPorDia: 1.35 },
  { distrito: "YANATILE", basuraPorDia: 1.35 },
  { distrito: "HUALGAYOC", basuraPorDia: 1.34 },
  { distrito: "JESUS", basuraPorDia: 1.34 },
  { distrito: "NUEVA ARICA", basuraPorDia: 1.34 },
  { distrito: "COASA", basuraPorDia: 1.33 },
  { distrito: "MARCARA", basuraPorDia: 1.33 },
  { distrito: "OLLACHEA", basuraPorDia: 1.32 },
  { distrito: "OROPESA", basuraPorDia: 1.32 },
  { distrito: "CASPISAPA", basuraPorDia: 1.32 },
  { distrito: "MATUCANA", basuraPorDia: 1.32 },
  { distrito: "TAMBOBAMBA", basuraPorDia: 1.31 },
  { distrito: "YURACYACU", basuraPorDia: 1.31 },
  { distrito: "JEBEROS", basuraPorDia: 1.31 },
  { distrito: "YUCAY", basuraPorDia: 1.3 },
  { distrito: "JAZAN", basuraPorDia: 1.3 },
  { distrito: "RIO SANTIAGO", basuraPorDia: 1.3 },
  { distrito: "HUANCABAMBA", basuraPorDia: 1.29 },
  { distrito: "CANTA", basuraPorDia: 1.29 },
  { distrito: "PAUCARA", basuraPorDia: 1.29 },
  { distrito: "HUACAYBAMBA", basuraPorDia: 1.29 },
  { distrito: "CONTUMAZA", basuraPorDia: 1.28 },
  { distrito: "IÑAPARI", basuraPorDia: 1.28 },
  { distrito: "HUIMBAYOC", basuraPorDia: 1.27 },
  { distrito: "LAS AMAZONAS", basuraPorDia: 1.27 },
  { distrito: "CANARIA", basuraPorDia: 1.27 },
  { distrito: "TRES DE DICIEMBRE", basuraPorDia: 1.26 },
  { distrito: "TINGO DE PONASA", basuraPorDia: 1.25 },
  { distrito: "CODO DEL POZUZO", basuraPorDia: 1.23 },
  { distrito: "JOSE DOMINGO CHOQUEHUANCA", basuraPorDia: 1.22 },
  { distrito: "UNION ASHANINKA", basuraPorDia: 1.22 },
  { distrito: "SANTA CRUZ DE FLORES", basuraPorDia: 1.22 },
  { distrito: "PISCOYACU", basuraPorDia: 1.21 },
  { distrito: "ANTABAMBA", basuraPorDia: 1.2 },
  { distrito: "TINTA", basuraPorDia: 1.2 },
  { distrito: "CABANA", basuraPorDia: 1.2 },
  { distrito: "JOSE MARIA QUIMPER", basuraPorDia: 1.2 },
  { distrito: "CHINCHERO", basuraPorDia: 1.2 },
  { distrito: "PUINAHUA", basuraPorDia: 1.2 },
  { distrito: "SAN FERNANDO", basuraPorDia: 1.19 },
  { distrito: "LA COIPA", basuraPorDia: 1.19 },
  { distrito: "VITOR", basuraPorDia: 1.19 },
  { distrito: "NAPO", basuraPorDia: 1.19 },
  { distrito: "SANCOS", basuraPorDia: 1.18 },
  { distrito: "PINTO RECODO", basuraPorDia: 1.17 },
  { distrito: "VELILLE", basuraPorDia: 1.17 },
  { distrito: "ZAPATERO", basuraPorDia: 1.17 },
  { distrito: "SAN LUIS", basuraPorDia: 1.17 },
  { distrito: "CORANI", basuraPorDia: 1.17 },
  { distrito: "RIPAN", basuraPorDia: 1.16 },
  { distrito: "TORATA", basuraPorDia: 1.16 },
  { distrito: "PAJARILLO", basuraPorDia: 1.15 },
  { distrito: "VILCAS HUAMAN", basuraPorDia: 1.14 },
  { distrito: "PASTAZA", basuraPorDia: 1.14 },
  { distrito: "MARANGANI", basuraPorDia: 1.12 },
  { distrito: "OMATE", basuraPorDia: 1.11 },
  { distrito: "CHOLON      ", basuraPorDia: 1.11 },
  { distrito: "EL INGENIO", basuraPorDia: 1.11 },
  { distrito: "SOCOTA", basuraPorDia: 1.11 },
  { distrito: "HUACRACHUCO", basuraPorDia: 1.1 },
  { distrito: "SAN RAFAEL", basuraPorDia: 1.1 },
  { distrito: "CHOLON", basuraPorDia: 1.09 },
  { distrito: "ACORIA", basuraPorDia: 1.09 },
  { distrito: "TIGRE", basuraPorDia: 1.08 },
  { distrito: "ATICO", basuraPorDia: 1.08 },
  { distrito: "SAN ANTON", basuraPorDia: 1.08 },
  { distrito: "NUÑOA", basuraPorDia: 1.08 },
  { distrito: "MOHO", basuraPorDia: 1.08 },
  { distrito: "LAMUD", basuraPorDia: 1.08 },
  { distrito: "QUEROCOTILLO", basuraPorDia: 1.08 },
  { distrito: "VITOR  ", basuraPorDia: 1.07 },
  { distrito: "LAMAY", basuraPorDia: 1.07 },
  { distrito: "MADRE DE DIOS   ", basuraPorDia: 1.06 },
  { distrito: "MACARI", basuraPorDia: 1.06 },
  { distrito: "ACOMAYO", basuraPorDia: 1.06 },
  { distrito: "QUILCAS", basuraPorDia: 1.05 },
  { distrito: "FLORIDA", basuraPorDia: 1.05 },
  { distrito: "HUAYOPATA", basuraPorDia: 1.05 },
  { distrito: "CCATCA", basuraPorDia: 1.04 },
  { distrito: "LIVITACA", basuraPorDia: 1.04 },
  { distrito: "CHIPURANA", basuraPorDia: 1.03 },
  { distrito: "YAUTAN", basuraPorDia: 1.03 },
  { distrito: "SAN MATEO", basuraPorDia: 1.03 },
  { distrito: "MADRE DE DIOS", basuraPorDia: 1.03 },
  { distrito: "YAVARI", basuraPorDia: 1.03 },
  { distrito: "FRIAS", basuraPorDia: 1.02 },
  { distrito: "QUILCAPUNCU", basuraPorDia: 1.02 },
  { distrito: "PALCAZU", basuraPorDia: 1.02 },
  { distrito: "JENARO HERRERA", basuraPorDia: 1.01 },
  { distrito: "QUELLOUNO", basuraPorDia: 1.01 },
  { distrito: "CANCHAQUE", basuraPorDia: 1.01 },
  { distrito: "PUCYURA", basuraPorDia: 1.01 },
  { distrito: "SAN PEDRO DE PUTINA PUNCU", basuraPorDia: 1.01 },
  { distrito: "LA JALCA", basuraPorDia: 1.0 },
  { distrito: "KOSÑIPATA", basuraPorDia: 1.0 },
  { distrito: "PAZOS", basuraPorDia: 1.0 },
  { distrito: "LURICOCHA", basuraPorDia: 1.0 },
  { distrito: "ITE", basuraPorDia: 0.99 },
  { distrito: "CHAVIN DE HUANTAR", basuraPorDia: 0.99 },
  { distrito: "YANTALO", basuraPorDia: 0.99 },
  { distrito: "ANDOAS ", basuraPorDia: 0.98 },
  { distrito: "SINCOS", basuraPorDia: 0.98 },
  { distrito: "RUMISAPA", basuraPorDia: 0.98 },
  { distrito: "ANDAHUAYLILLAS", basuraPorDia: 0.98 },
  { distrito: "MORONA", basuraPorDia: 0.97 },
  { distrito: "SAN PEDRO DE PUTINA PUNCO", basuraPorDia: 0.97 },
  { distrito: "CANGALLO", basuraPorDia: 0.97 },
  { distrito: "COPALLIN", basuraPorDia: 0.97 },
  { distrito: "SANTA MARIA DEL VALLE ", basuraPorDia: 0.96 },
  { distrito: "TRES UNIDOS", basuraPorDia: 0.96 },
  { distrito: "CHONTALI", basuraPorDia: 0.95 },
  { distrito: "ACORA", basuraPorDia: 0.95 },
  { distrito: "LOS MOROCHUCOS", basuraPorDia: 0.95 },
  { distrito: "HUAROCONDO", basuraPorDia: 0.95 },
  { distrito: "SAN JOSE DE QUERO", basuraPorDia: 0.95 },
  { distrito: "SITACOCHA", basuraPorDia: 0.95 },
  { distrito: "POMATA", basuraPorDia: 0.95 },
  { distrito: "JAQUI", basuraPorDia: 0.94 },
  { distrito: "CHAPARRA", basuraPorDia: 0.94 },
  { distrito: "SAN GABAN", basuraPorDia: 0.94 },
  { distrito: "CHUQUIBAMBILLA", basuraPorDia: 0.93 },
  { distrito: "TARAY", basuraPorDia: 0.93 },
  { distrito: "CATAC", basuraPorDia: 0.92 },
  { distrito: "COMBAPATA", basuraPorDia: 0.91 },
  { distrito: "SANTA MARIA DEL MAR", basuraPorDia: 0.91 },
  { distrito: "CUÑUMBUQUI", basuraPorDia: 0.9 },
  { distrito: "PAPAPLAYA", basuraPorDia: 0.9 },
  { distrito: "MANUEL ANTONIO MESONES MURO", basuraPorDia: 0.9 },
  { distrito: "SANTA ROSA DE QUIVES", basuraPorDia: 0.9 },
  { distrito: "ACOPIA", basuraPorDia: 0.9 },
  { distrito: "CHILLIA", basuraPorDia: 0.9 },
  { distrito: "POSIC", basuraPorDia: 0.89 },
  { distrito: "CABANILLAS", basuraPorDia: 0.89 },
  { distrito: "ZURITE", basuraPorDia: 0.89 },
  { distrito: "MUQUIYAUYO", basuraPorDia: 0.88 },
  { distrito: "SANTA MARIA DEL VALLE", basuraPorDia: 0.88 },
  { distrito: "COLASAY", basuraPorDia: 0.88 },
  { distrito: "INGENIO", basuraPorDia: 0.87 },
  { distrito: "CABANACONDE", basuraPorDia: 0.87 },
  { distrito: "CUYOCUYO", basuraPorDia: 0.87 },
  { distrito: "TARICA", basuraPorDia: 0.87 },
  { distrito: "TOURNAVISTA", basuraPorDia: 0.87 },
  { distrito: "MARIAS", basuraPorDia: 0.87 },
  { distrito: "SINSICAP", basuraPorDia: 0.87 },
  { distrito: "CARAVELI", basuraPorDia: 0.87 },
  { distrito: "HUAY-HUAY", basuraPorDia: 0.86 },
  { distrito: "LAJAS", basuraPorDia: 0.86 },
  { distrito: "CHINCHEROS", basuraPorDia: 0.86 },
  { distrito: "COTAHUASI", basuraPorDia: 0.85 },
  { distrito: "CHAVINILLO", basuraPorDia: 0.85 },
  { distrito: "CHILETE", basuraPorDia: 0.84 },
  { distrito: "PUÑOS", basuraPorDia: 0.84 },
  { distrito: "CAMANTI", basuraPorDia: 0.84 },
  { distrito: "TOMAY KICHWA", basuraPorDia: 0.83 },
  { distrito: "MARIANO NICOLAS VALCARCEL", basuraPorDia: 0.83 },
  { distrito: "IPARIA", basuraPorDia: 0.83 },
  { distrito: "SARHUA", basuraPorDia: 0.83 },
  { distrito: "HUARANCHAL", basuraPorDia: 0.82 },
  { distrito: "HUACULLANI", basuraPorDia: 0.82 },
  { distrito: "JANGAS", basuraPorDia: 0.82 },
  { distrito: "COLCABAMBA     ", basuraPorDia: 0.81 },
  { distrito: "SAN PEDRO DE CORIS", basuraPorDia: 0.81 },
  { distrito: "SAN FRANCISCO DE ASIS DE YARUSYACAN", basuraPorDia: 0.81 },
  { distrito: "LUYA", basuraPorDia: 0.81 },
  { distrito: "EDUARDO VILLANUEVA", basuraPorDia: 0.81 },
  { distrito: "CACHICADAN", basuraPorDia: 0.81 },
  { distrito: "OMACHA", basuraPorDia: 0.81 },
  { distrito: "YORONGOS", basuraPorDia: 0.81 },
  { distrito: "HUACAR", basuraPorDia: 0.8 },
  { distrito: "PACAYCASA", basuraPorDia: 0.8 },
  { distrito: "COMANDANTE NOEL", basuraPorDia: 0.8 },
  { distrito: "AUCARA", basuraPorDia: 0.8 },
  { distrito: "YAMANGO", basuraPorDia: 0.8 },
  { distrito: "EL ESLABON", basuraPorDia: 0.8 },
  { distrito: "YANQUE", basuraPorDia: 0.79 },
  { distrito: "HUANOQUITE", basuraPorDia: 0.79 },
  { distrito: "HUANDO", basuraPorDia: 0.79 },
  { distrito: "HUANCARANI", basuraPorDia: 0.79 },
  { distrito: "PUQUINA", basuraPorDia: 0.78 },
  { distrito: "VICCO", basuraPorDia: 0.78 },
  { distrito: "ALCA", basuraPorDia: 0.78 },
  { distrito: "MANITEA", basuraPorDia: 0.78 },
  { distrito: "PAUCAS", basuraPorDia: 0.78 },
  { distrito: "MAÑAZO", basuraPorDia: 0.78 },
  { distrito: "TICAPAMPA", basuraPorDia: 0.78 },
  { distrito: "VILCABAMBA", basuraPorDia: 0.77 },
  { distrito: "TOURNAVISTA  ", basuraPorDia: 0.77 },
  { distrito: "MANCOS", basuraPorDia: 0.77 },
  { distrito: "HUAMANGUILLA", basuraPorDia: 0.77 },
  { distrito: "SARIN", basuraPorDia: 0.77 },
  { distrito: "CURGOS", basuraPorDia: 0.76 },
  { distrito: "ALTO INAMBARI", basuraPorDia: 0.76 },
  { distrito: "LIMBANI", basuraPorDia: 0.76 },
  { distrito: "VISCHONGO", basuraPorDia: 0.76 },
  { distrito: "RIO GRANDE", basuraPorDia: 0.76 },
  { distrito: "MUÑANI", basuraPorDia: 0.75 },
  { distrito: "HABANA", basuraPorDia: 0.75 },
  { distrito: "CAPELO", basuraPorDia: 0.75 },
  { distrito: "ACOCRO", basuraPorDia: 0.75 },
  { distrito: "PARINARI  ", basuraPorDia: 0.74 },
  { distrito: "CULEBRAS", basuraPorDia: 0.74 },
  { distrito: "CHAVIN DE PARIARCA", basuraPorDia: 0.74 },
  { distrito: "MOLLEPATA", basuraPorDia: 0.74 },
  { distrito: "SAN JUAN DEL ORO", basuraPorDia: 0.74 },
  { distrito: "CHIGUATA", basuraPorDia: 0.74 },
  { distrito: "YANAOCA", basuraPorDia: 0.74 },
  { distrito: "SHATOJA", basuraPorDia: 0.74 },
  { distrito: "PARINARI", basuraPorDia: 0.73 },
  { distrito: "CHACOCHE", basuraPorDia: 0.73 },
  { distrito: "TANTARICA", basuraPorDia: 0.73 },
  { distrito: "PHARA", basuraPorDia: 0.73 },
  { distrito: "COTABAMBAS", basuraPorDia: 0.73 },
  { distrito: "PICHACANI", basuraPorDia: 0.73 },
  { distrito: "TINCO", basuraPorDia: 0.73 },
  { distrito: "QUEROBAMBA", basuraPorDia: 0.72 },
  { distrito: "SAN LORENZO", basuraPorDia: 0.72 },
  { distrito: "LEIMEBAMBA", basuraPorDia: 0.72 },
  { distrito: "COLQUIOC", basuraPorDia: 0.72 },
  { distrito: "ANGASMARCA", basuraPorDia: 0.72 },
  { distrito: "PAMPACOLCA", basuraPorDia: 0.72 },
  { distrito: "HUACHAC", basuraPorDia: 0.71 },
  { distrito: "LLAYLLA", basuraPorDia: 0.71 },
  { distrito: "CHACAYAN", basuraPorDia: 0.71 },
  { distrito: "YARABAMBA", basuraPorDia: 0.71 },
  { distrito: "CHINCHAO     ", basuraPorDia: 0.71 },
  { distrito: "JAMALCA", basuraPorDia: 0.71 },
  { distrito: "TARACO", basuraPorDia: 0.71 },
  { distrito: "SANTA CATALINA DE MOSSA", basuraPorDia: 0.71 },
  { distrito: "LOCUMBA", basuraPorDia: 0.7 },
  { distrito: "TAPUC", basuraPorDia: 0.7 },
  { distrito: "OCOBAMBA", basuraPorDia: 0.7 },
  { distrito: "AJOYANI", basuraPorDia: 0.7 },
  { distrito: "LLIPATA", basuraPorDia: 0.7 },
  { distrito: "SAN PEDRO DE CAJAS", basuraPorDia: 0.7 },
  { distrito: "PURUS", basuraPorDia: 0.7 },
  { distrito: "ROSARIO", basuraPorDia: 0.7 },
  { distrito: "HUANCAS", basuraPorDia: 0.69 },
  { distrito: "JUAN ESPINOZA MEDRANO", basuraPorDia: 0.69 },
  { distrito: "HUACHIS", basuraPorDia: 0.69 },
  { distrito: "CAJATAMBO", basuraPorDia: 0.69 },
  { distrito: "YUYAPICHIS", basuraPorDia: 0.68 },
  { distrito: "LAMPA", basuraPorDia: 0.68 },
  { distrito: "CHUMPI", basuraPorDia: 0.68 },
  { distrito: "MARANURA", basuraPorDia: 0.68 },
  { distrito: "ARENAL", basuraPorDia: 0.68 },
  { distrito: "MARA", basuraPorDia: 0.68 },
  { distrito: "HUERTAS", basuraPorDia: 0.68 },
  { distrito: "LA MORADA", basuraPorDia: 0.67 },
  { distrito: "AIJA", basuraPorDia: 0.67 },
  { distrito: "LLAMELLIN", basuraPorDia: 0.67 },
  { distrito: "AYAPATA", basuraPorDia: 0.67 },
  { distrito: "TARATA", basuraPorDia: 0.67 },
  { distrito: "VILLA VIRGEN  ", basuraPorDia: 0.67 },
  { distrito: "HONORIA", basuraPorDia: 0.66 },
  { distrito: "CHACAS", basuraPorDia: 0.66 },
  { distrito: "CHINCHAO", basuraPorDia: 0.66 },
  { distrito: "LEONOR ORDOÑEZ", basuraPorDia: 0.66 },
  { distrito: "CIELO PUNCO", basuraPorDia: 0.66 },
  { distrito: "LUCANAS", basuraPorDia: 0.66 },
  { distrito: "VILLA VIRGEN", basuraPorDia: 0.66 },
  { distrito: "CATACHE", basuraPorDia: 0.66 },
  { distrito: "YACUS  ", basuraPorDia: 0.65 },
  { distrito: "PADRE MARQUEZ", basuraPorDia: 0.65 },
  { distrito: "LA MORADA   ", basuraPorDia: 0.65 },
  { distrito: "CASTROVIRREYNA", basuraPorDia: 0.65 },
  { distrito: "MARGOS   ", basuraPorDia: 0.65 },
  { distrito: "LOCROJA", basuraPorDia: 0.65 },
  { distrito: "CHAMACA", basuraPorDia: 0.65 },
  { distrito: "PACAIPAMPA", basuraPorDia: 0.64 },
  { distrito: "LLALLI", basuraPorDia: 0.64 },
  { distrito: "SAYAPULLO", basuraPorDia: 0.64 },
  { distrito: "SANTA TERESA", basuraPorDia: 0.64 },
  { distrito: "POTONI", basuraPorDia: 0.64 },
  { distrito: "NAMBALLE", basuraPorDia: 0.64 },
  { distrito: "NAMORA", basuraPorDia: 0.64 },
  { distrito: "HUANCARQUI", basuraPorDia: 0.63 },
  { distrito: "CHAVIÑA", basuraPorDia: 0.63 },
  { distrito: "AGUA BLANCA", basuraPorDia: 0.63 },
  { distrito: "ATAURA", basuraPorDia: 0.63 },
  { distrito: "HUAQUIRCA", basuraPorDia: 0.63 },
  { distrito: "EL CENEPA", basuraPorDia: 0.63 },
  { distrito: "SAN ANTONIO DE CACHI", basuraPorDia: 0.62 },
  { distrito: "CHIPAO", basuraPorDia: 0.62 },
  { distrito: "ANCHONGA", basuraPorDia: 0.62 },
  { distrito: "HUARMACA", basuraPorDia: 0.62 },
  { distrito: "EL CENEPA ", basuraPorDia: 0.61 },
  { distrito: "CHUGAY", basuraPorDia: 0.61 },
  { distrito: "NUEVE DE JULIO", basuraPorDia: 0.61 },
  { distrito: "PARAS", basuraPorDia: 0.61 },
  { distrito: "SAN ROQUE DE CUMBAZA", basuraPorDia: 0.61 },
  { distrito: "CANCHAYLLO", basuraPorDia: 0.61 },
  { distrito: "ACCHA", basuraPorDia: 0.61 },
  { distrito: "PISCOBAMBA", basuraPorDia: 0.61 },
  { distrito: "CONDEBAMBA", basuraPorDia: 0.6 },
  { distrito: "LALAQUIZ", basuraPorDia: 0.6 },
  { distrito: "YACUS", basuraPorDia: 0.6 },
  { distrito: "RANRAHIRCA", basuraPorDia: 0.6 },
  { distrito: "CHICLA", basuraPorDia: 0.6 },
  { distrito: "MARGOS", basuraPorDia: 0.6 },
  { distrito: "QUEROCOTO", basuraPorDia: 0.6 },
  { distrito: "CAHUAPANAS", basuraPorDia: 0.59 },
  { distrito: "HUAMBOS", basuraPorDia: 0.59 },
  { distrito: "COJATA", basuraPorDia: 0.59 },
  { distrito: "MARAS", basuraPorDia: 0.59 },
  { distrito: "NINACACA", basuraPorDia: 0.59 },
  { distrito: "EL MANTARO", basuraPorDia: 0.59 },
  { distrito: "CARAPO", basuraPorDia: 0.59 },
  { distrito: "ZEPITA", basuraPorDia: 0.58 },
  { distrito: "SANGARARA", basuraPorDia: 0.58 },
  { distrito: "UNION PROGRESO", basuraPorDia: 0.58 },
  { distrito: "SACANCHE", basuraPorDia: 0.58 },
  { distrito: "CORONGO", basuraPorDia: 0.58 },
  { distrito: "BALSAPUERTO", basuraPorDia: 0.58 },
  { distrito: "PUNCHAO", basuraPorDia: 0.57 },
  { distrito: "KISHUARA", basuraPorDia: 0.57 },
  { distrito: "SAN FCO.DE ASIS DE YARUSYAC", basuraPorDia: 0.57 },
  { distrito: "YAUCA", basuraPorDia: 0.57 },
  { distrito: "VIRACO", basuraPorDia: 0.56 },
  { distrito: "PILLPINTO", basuraPorDia: 0.56 },
  { distrito: "PACHIA", basuraPorDia: 0.56 },
  { distrito: "HUANCAPI", basuraPorDia: 0.56 },
  { distrito: "QUILLO", basuraPorDia: 0.56 },
  { distrito: "PARIACOTO", basuraPorDia: 0.56 },
  { distrito: "CHANGUILLO", basuraPorDia: 0.56 },
  { distrito: "PACARAOS", basuraPorDia: 0.56 },
  { distrito: "COLQUEMARCA", basuraPorDia: 0.56 },
  { distrito: "ANDARAPA", basuraPorDia: 0.55 },
  { distrito: "QUINUA", basuraPorDia: 0.55 },
  { distrito: "SAN MIGUEL DE CAURI", basuraPorDia: 0.55 },
  { distrito: "LOMAS", basuraPorDia: 0.55 },
  { distrito: "PALLPATA", basuraPorDia: 0.55 },
  { distrito: "TOTOS", basuraPorDia: 0.55 },
  { distrito: "LONGOTEA", basuraPorDia: 0.55 },
  { distrito: "HUAYTARA", basuraPorDia: 0.55 },
  { distrito: "SANTA ROSA DE ALTO YANAJANCA", basuraPorDia: 0.54 },
  { distrito: "URANMARCA", basuraPorDia: 0.54 },
  { distrito: "VILQUE CHICO", basuraPorDia: 0.54 },
  { distrito: "ENCAÑADA", basuraPorDia: 0.54 },
  { distrito: "CALANGO", basuraPorDia: 0.54 },
  { distrito: "JUMBILLA", basuraPorDia: 0.54 },
  { distrito: "DANIEL ALOMIA ROBLES", basuraPorDia: 0.54 },
  { distrito: "ARAPA", basuraPorDia: 0.54 },
  { distrito: "PALCAMAYO", basuraPorDia: 0.53 },
  { distrito: "JOSE SABOGAL", basuraPorDia: 0.53 },
  { distrito: "POROTO", basuraPorDia: 0.53 },
  { distrito: "HUACCANA", basuraPorDia: 0.53 },
  { distrito: "MARISCAL BENAVIDES", basuraPorDia: 0.53 },
  { distrito: "SANTA ROSA DE ALTO YANAJANCA   ", basuraPorDia: 0.53 },
  { distrito: "UCHUMARCA", basuraPorDia: 0.53 },
  { distrito: "CANDARAVE", basuraPorDia: 0.53 },
  { distrito: "HUAROS", basuraPorDia: 0.53 },
  { distrito: "ANCHIHUAY", basuraPorDia: 0.52 },
  { distrito: "COLCAMAR", basuraPorDia: 0.52 },
  { distrito: "CHALLABAMBA", basuraPorDia: 0.52 },
  { distrito: "SAN LORENZO DE QUINTI", basuraPorDia: 0.52 },
  { distrito: "HUATASANI", basuraPorDia: 0.52 },
  { distrito: "HUAROCHIRI", basuraPorDia: 0.52 },
  { distrito: "JULCAMARCA", basuraPorDia: 0.52 },
  { distrito: "EL PORVENIR", basuraPorDia: 0.51 },
  { distrito: "APARICIO POMARES", basuraPorDia: 0.51 },
  { distrito: "SAN LUIS DE SHUARO", basuraPorDia: 0.51 },
  { distrito: "CARACOTO  ", basuraPorDia: 0.51 },
  { distrito: "POZUZO", basuraPorDia: 0.51 },
  { distrito: "PILCUYO", basuraPorDia: 0.51 },
  { distrito: "CARACOTO", basuraPorDia: 0.5 },
  { distrito: "HUALLAGA", basuraPorDia: 0.5 },
  { distrito: "COLQUEPATA", basuraPorDia: 0.5 },
  { distrito: "COATA", basuraPorDia: 0.5 },
  { distrito: "PACHAS", basuraPorDia: 0.5 },
  { distrito: "ANCHIHUAY  ", basuraPorDia: 0.5 },
  { distrito: "POMAHUACA", basuraPorDia: 0.5 },
  { distrito: "OCROS   ", basuraPorDia: 0.5 },
  { distrito: "SANTA CRUZ DE COCACHACRA", basuraPorDia: 0.5 },
  { distrito: "EL PORVENIR   ", basuraPorDia: 0.5 },
  { distrito: "INAHUAYA", basuraPorDia: 0.5 },
  { distrito: "YAMBRASBAMBA", basuraPorDia: 0.49 },
  { distrito: "PARCO", basuraPorDia: 0.49 },
  { distrito: "PACCHA", basuraPorDia: 0.49 },
  { distrito: "CARMEN SALCEDO", basuraPorDia: 0.49 },
  { distrito: "HUABAL", basuraPorDia: 0.49 },
  { distrito: "MIRGAS", basuraPorDia: 0.49 },
  { distrito: "MARISCAL CASTILLA", basuraPorDia: 0.49 },
  { distrito: "GOYLLARISQUIZGA", basuraPorDia: 0.49 },
  { distrito: "SANTA LUCIA", basuraPorDia: 0.49 },
  { distrito: "RONDOCAN", basuraPorDia: 0.49 },
  { distrito: "SABAINO", basuraPorDia: 0.49 },
  { distrito: "CACHIMAYO", basuraPorDia: 0.49 },
  { distrito: "HUARIPAMPA", basuraPorDia: 0.48 },
  { distrito: "OCALLI", basuraPorDia: 0.48 },
  { distrito: "YANAHUAYA", basuraPorDia: 0.48 },
  { distrito: "MARCO", basuraPorDia: 0.48 },
  { distrito: "CARUMAS", basuraPorDia: 0.48 },
  { distrito: "SALPO", basuraPorDia: 0.48 },
  { distrito: "CONGALLA", basuraPorDia: 0.48 },
  { distrito: "SAQUENA", basuraPorDia: 0.48 },
  { distrito: "TINGO DE SAPOSOA", basuraPorDia: 0.48 },
  { distrito: "HUARICOLCA", basuraPorDia: 0.48 },
  { distrito: "TURPO", basuraPorDia: 0.48 },
  { distrito: "CABANILLA", basuraPorDia: 0.48 },
  { distrito: "MUQUI", basuraPorDia: 0.47 },
  { distrito: "KUMPIRUSHIATO", basuraPorDia: 0.47 },
  { distrito: "INCAHUASI", basuraPorDia: 0.47 },
  { distrito: "CHALACO", basuraPorDia: 0.47 },
  { distrito: "CUSCA", basuraPorDia: 0.47 },
  { distrito: "LLAPO", basuraPorDia: 0.47 },
  { distrito: "CUSIPATA", basuraPorDia: 0.47 },
  { distrito: "PACHANGARA", basuraPorDia: 0.47 },
  { distrito: "SANTILLANA", basuraPorDia: 0.47 },
  { distrito: "SAN PEDRO DE CHANA", basuraPorDia: 0.47 },
  { distrito: "CHURUBAMBA", basuraPorDia: 0.47 },
  { distrito: "HUANCARAYLLA", basuraPorDia: 0.46 },
  { distrito: "SAN PEDRO DE CASTA", basuraPorDia: 0.46 },
  { distrito: "YURUA", basuraPorDia: 0.46 },
  { distrito: "CHECACUPE", basuraPorDia: 0.46 },
  { distrito: "MEJIA", basuraPorDia: 0.46 },
  { distrito: "SALLIQUE", basuraPorDia: 0.46 },
  { distrito: "PIRA", basuraPorDia: 0.46 },
  { distrito: "QUICHUAY", basuraPorDia: 0.46 },
  { distrito: "CARABAMBA", basuraPorDia: 0.45 },
  { distrito: "BULDIBUYO", basuraPorDia: 0.45 },
  { distrito: "OCROS", basuraPorDia: 0.45 },
  { distrito: "TABACONAS", basuraPorDia: 0.45 },
  { distrito: "INCLAN", basuraPorDia: 0.45 },
  { distrito: "SHILLA", basuraPorDia: 0.45 },
  { distrito: "SAPILLICA", basuraPorDia: 0.45 },
  { distrito: "OBAS", basuraPorDia: 0.44 },
  { distrito: "PACUCHA", basuraPorDia: 0.44 },
  { distrito: "HUAMALI", basuraPorDia: 0.44 },
  { distrito: "SANTIAGO DE LUCANAMARCA", basuraPorDia: 0.44 },
  { distrito: "MOLINOS", basuraPorDia: 0.44 },
  { distrito: "JULCAN", basuraPorDia: 0.44 },
  { distrito: "CHUQUIS", basuraPorDia: 0.44 },
  { distrito: "CHINCHAYPUJIO", basuraPorDia: 0.44 },
  { distrito: "LACHAQUI", basuraPorDia: 0.44 },
  { distrito: "PAUCAR", basuraPorDia: 0.44 },
  { distrito: "SAN ANDRES DE CUTERVO", basuraPorDia: 0.44 },
  { distrito: "APATA", basuraPorDia: 0.44 },
  { distrito: "MONTERO", basuraPorDia: 0.44 },
  { distrito: "SANTO DOMINGO", basuraPorDia: 0.43 },
  { distrito: "COYLLURQUI", basuraPorDia: 0.43 },
  { distrito: "PACHACONAS", basuraPorDia: 0.43 },
  { distrito: "CAYNA", basuraPorDia: 0.43 },
  { distrito: "PUYCA", basuraPorDia: 0.43 },
  { distrito: "PILLUANA", basuraPorDia: 0.43 },
  { distrito: "HUASMIN", basuraPorDia: 0.42 },
  { distrito: "AQUIA", basuraPorDia: 0.42 },
  { distrito: "ANCO", basuraPorDia: 0.42 },
  { distrito: "PALLASCA", basuraPorDia: 0.42 },
  { distrito: "SURCO", basuraPorDia: 0.42 },
  { distrito: "SANTIAGO DE CHALLAS", basuraPorDia: 0.42 },
  { distrito: "CAIRANI", basuraPorDia: 0.42 },
  { distrito: "JACAS GRANDE", basuraPorDia: 0.42 },
  { distrito: "CONGAS", basuraPorDia: 0.42 },
  { distrito: "PAROBAMBA", basuraPorDia: 0.42 },
  { distrito: "AHUAYRO", basuraPorDia: 0.42 },
  { distrito: "MOLLEBAMBA", basuraPorDia: 0.41 },
  { distrito: "LONGAR", basuraPorDia: 0.41 },
  { distrito: "SAN DAMIAN", basuraPorDia: 0.41 },
  { distrito: "LOBITOS", basuraPorDia: 0.41 },
  { distrito: "UNION AGUA BLANCA", basuraPorDia: 0.41 },
  { distrito: "YAQUERANA", basuraPorDia: 0.41 },
  { distrito: "SAN SALVADOR", basuraPorDia: 0.41 },
  { distrito: "MATO", basuraPorDia: 0.41 },
  { distrito: "ZUÑIGA", basuraPorDia: 0.41 },
  { distrito: "PUYUSCA", basuraPorDia: 0.41 },
  { distrito: "SUCRE", basuraPorDia: 0.41 },
  { distrito: "CCOCHACCASA", basuraPorDia: 0.41 },
  { distrito: "SANTA ROSA DE OCOPA", basuraPorDia: 0.41 },
  { distrito: "HUACHOCOLPA", basuraPorDia: 0.41 },
  { distrito: "SINGA", basuraPorDia: 0.41 },
  { distrito: "PUCAYACU   ", basuraPorDia: 0.41 },
  { distrito: "QUICACHA", basuraPorDia: 0.41 },
  { distrito: "TICRAPO", basuraPorDia: 0.41 },
  { distrito: "HUAYLLABAMBA", basuraPorDia: 0.41 },
  { distrito: "YAQUERANA   ", basuraPorDia: 0.41 },
  { distrito: "CHAPIMARCA", basuraPorDia: 0.4 },
  { distrito: "SAN JUAN DE JARPA", basuraPorDia: 0.4 },
  { distrito: "ACOS", basuraPorDia: 0.4 },
  { distrito: "CHACA", basuraPorDia: 0.4 },
  { distrito: "CUCHUMBAYA", basuraPorDia: 0.4 },
  { distrito: "HUACCHIS", basuraPorDia: 0.39 },
  { distrito: "SHANAO", basuraPorDia: 0.39 },
  { distrito: "HUANCA-HUANCA", basuraPorDia: 0.39 },
  { distrito: "TAURIJA", basuraPorDia: 0.39 },
  { distrito: "CHACA   ", basuraPorDia: 0.39 },
  { distrito: "PUCAYACU", basuraPorDia: 0.39 },
  { distrito: "LAMBRAMA", basuraPorDia: 0.39 },
  { distrito: "SIMBAL", basuraPorDia: 0.39 },
  { distrito: "RANRACANCHA", basuraPorDia: 0.39 },
  { distrito: "HUANCASPATA", basuraPorDia: 0.39 },
  { distrito: "IHUARI", basuraPorDia: 0.39 },
  { distrito: "SORAS", basuraPorDia: 0.39 },
  { distrito: "ALTO NANAY  ", basuraPorDia: 0.39 },
  { distrito: "COLCHA", basuraPorDia: 0.39 },
  { distrito: "CACERES DEL PERU", basuraPorDia: 0.39 },
  { distrito: "ALTO NANAY", basuraPorDia: 0.39 },
  { distrito: "CALANA", basuraPorDia: 0.38 },
  { distrito: "PARURO", basuraPorDia: 0.38 },
  { distrito: "COSME ", basuraPorDia: 0.38 },
  { distrito: "SOCOS", basuraPorDia: 0.38 },
  { distrito: "RIO MAGDALENA", basuraPorDia: 0.38 },
  { distrito: "OCAÑA", basuraPorDia: 0.38 },
  { distrito: "SICCHEZ", basuraPorDia: 0.38 },
  { distrito: "PICHOS   ", basuraPorDia: 0.38 },
  { distrito: "ANDOAS", basuraPorDia: 0.38 },
  { distrito: "MANZANARES", basuraPorDia: 0.38 },
  { distrito: "HUAMBO", basuraPorDia: 0.38 },
  { distrito: "LLOCLLAPAMPA", basuraPorDia: 0.38 },
  { distrito: "MANU   ", basuraPorDia: 0.37 },
  { distrito: "SONDOR", basuraPorDia: 0.37 },
  { distrito: "MACA", basuraPorDia: 0.37 },
  { distrito: "ORURILLO", basuraPorDia: 0.37 },
  { distrito: "PONTO", basuraPorDia: 0.37 },
  { distrito: "HUALLA", basuraPorDia: 0.37 },
  { distrito: "OMIA", basuraPorDia: 0.37 },
  { distrito: "INKAWASI  ", basuraPorDia: 0.37 },
  { distrito: "PACCHO", basuraPorDia: 0.37 },
  { distrito: "HUASO", basuraPorDia: 0.37 },
  { distrito: "COSME", basuraPorDia: 0.37 },
  { distrito: "COPA", basuraPorDia: 0.37 },
  { distrito: "CALLALLI", basuraPorDia: 0.37 },
  { distrito: "CONDURIRI", basuraPorDia: 0.37 },
  { distrito: "CONIMA", basuraPorDia: 0.37 },
  { distrito: "HUAYNACOTAS", basuraPorDia: 0.37 },
  { distrito: "CUTURAPI", basuraPorDia: 0.37 },
  { distrito: "ACOSTAMBO", basuraPorDia: 0.36 },
  { distrito: "SANTIAGO DE PISCHA", basuraPorDia: 0.36 },
  { distrito: "PISACOMA", basuraPorDia: 0.36 },
  { distrito: "MANU", basuraPorDia: 0.36 },
  { distrito: "ROCCHACC", basuraPorDia: 0.36 },
  { distrito: "CARAYBAMBA", basuraPorDia: 0.36 },
  { distrito: "INKAWASI", basuraPorDia: 0.36 },
  { distrito: "MAGDALENA", basuraPorDia: 0.36 },
  { distrito: "RAHUAPAMPA", basuraPorDia: 0.36 },
  { distrito: "KUNTURKANKI", basuraPorDia: 0.36 },
  { distrito: "MACHE", basuraPorDia: 0.36 },
  { distrito: "SAN PEDRO DE CHUNAN", basuraPorDia: 0.36 },
  { distrito: "AGALLPAMPA", basuraPorDia: 0.36 },
  { distrito: "PICHOS", basuraPorDia: 0.35 },
  { distrito: "TINGO", basuraPorDia: 0.35 },
  { distrito: "QUERCO", basuraPorDia: 0.35 },
  { distrito: "CHONGOS ALTO", basuraPorDia: 0.35 },
  { distrito: "LLUSCO", basuraPorDia: 0.35 },
  { distrito: "EL PARCO", basuraPorDia: 0.35 },
  { distrito: "COPORAQUE", basuraPorDia: 0.35 },
  { distrito: "LARAMATE", basuraPorDia: 0.35 },
  { distrito: "SANTIAGO DE PAUCARAY", basuraPorDia: 0.35 },
  { distrito: "ROCCHACC   ", basuraPorDia: 0.35 },
  { distrito: "CHINGAS", basuraPorDia: 0.35 },
  { distrito: "VILCANCHOS", basuraPorDia: 0.35 },
  { distrito: "CHALAMARCA", basuraPorDia: 0.35 },
  { distrito: "LA LIBERTAD DE PALLAN", basuraPorDia: 0.35 },
  { distrito: "TANTA", basuraPorDia: 0.35 },
  { distrito: "HUAYRAPATA", basuraPorDia: 0.35 },
  { distrito: "IGUAIN", basuraPorDia: 0.34 },
  { distrito: "PACARAN", basuraPorDia: 0.34 },
  { distrito: "YAUYA", basuraPorDia: 0.34 },
  { distrito: "PUSI ", basuraPorDia: 0.34 },
  { distrito: "SANTO DOMINGO DE LA CAPILLA", basuraPorDia: 0.34 },
  { distrito: "TRITA", basuraPorDia: 0.34 },
  { distrito: "YAUYUCAN", basuraPorDia: 0.33 },
  { distrito: "SITABAMBA", basuraPorDia: 0.33 },
  { distrito: "SUSAPAYA", basuraPorDia: 0.33 },
  { distrito: "PUSI", basuraPorDia: 0.33 },
  { distrito: "AHUAYCHA", basuraPorDia: 0.33 },
  { distrito: "SHIPASBAMBA", basuraPorDia: 0.33 },
  { distrito: "VINCHOS", basuraPorDia: 0.33 },
  { distrito: "VIZCATAN DEL ENE", basuraPorDia: 0.33 },
  { distrito: "SACSAMARCA", basuraPorDia: 0.33 },
  { distrito: "TUNAN MARCA", basuraPorDia: 0.33 },
  { distrito: "ANTA", basuraPorDia: 0.33 },
  { distrito: "HUACACHI", basuraPorDia: 0.33 },
  { distrito: "PACCARITAMBO", basuraPorDia: 0.32 },
  { distrito: "LLAPA", basuraPorDia: 0.32 },
  { distrito: "PUEBLO NUEVO  ", basuraPorDia: 0.32 },
  { distrito: "ACRAQUIA", basuraPorDia: 0.32 },
  { distrito: "SANTA ANA DE HUAYCAHUACHO", basuraPorDia: 0.32 },
  { distrito: "SAN JUAN DE IRIS", basuraPorDia: 0.32 },
  { distrito: "COMAS", basuraPorDia: 0.32 },
  { distrito: "ACZO", basuraPorDia: 0.32 },
  { distrito: "QUIÑOTA", basuraPorDia: 0.32 },
  { distrito: "CCAPI", basuraPorDia: 0.32 },
  { distrito: "LAS PIRIAS", basuraPorDia: 0.32 },
  { distrito: "VIZCATAN DEL ENE   ", basuraPorDia: 0.32 },
  { distrito: "OYOLO", basuraPorDia: 0.32 },
  { distrito: "UBINAS", basuraPorDia: 0.32 },
  { distrito: "CAPACMARCA", basuraPorDia: 0.32 },
  { distrito: "MASIN", basuraPorDia: 0.32 },
  { distrito: "LLACANORA", basuraPorDia: 0.32 },
  { distrito: "PARATIA", basuraPorDia: 0.32 },
  { distrito: "MATARA", basuraPorDia: 0.32 },
  { distrito: "ACOBAMBA", basuraPorDia: 0.32 },
  { distrito: "CHUPURO", basuraPorDia: 0.32 },
  { distrito: "ACOS VINCHOS", basuraPorDia: 0.32 },
  { distrito: "CATAHUASI", basuraPorDia: 0.31 },
  { distrito: "COCHORCO", basuraPorDia: 0.31 },
  { distrito: "TAPO", basuraPorDia: 0.31 },
  { distrito: "CHAMBARA", basuraPorDia: 0.31 },
  { distrito: "PACLLON", basuraPorDia: 0.31 },
  { distrito: "UMARI  ", basuraPorDia: 0.31 },
  { distrito: "TISCO", basuraPorDia: 0.31 },
  { distrito: "PACA", basuraPorDia: 0.31 },
  { distrito: "SAN BARTOLOME", basuraPorDia: 0.31 },
  { distrito: "ICHUÑA", basuraPorDia: 0.31 },
  { distrito: "TILALI", basuraPorDia: 0.31 },
  { distrito: "CAJACAY", basuraPorDia: 0.31 },
  { distrito: "YUNGAR", basuraPorDia: 0.31 },
  { distrito: "SAN PABLO DE PILLAO", basuraPorDia: 0.31 },
  { distrito: "COTARUSE", basuraPorDia: 0.31 },
  { distrito: "HUANCANO", basuraPorDia: 0.31 },
  { distrito: "AMASHCA", basuraPorDia: 0.31 },
  { distrito: "CAYARA", basuraPorDia: 0.31 },
  { distrito: "CONCHAMARCA", basuraPorDia: 0.3 },
  { distrito: "CAJA", basuraPorDia: 0.3 },
  { distrito: "CHADIN", basuraPorDia: 0.3 },
  { distrito: "PUEBLO NUEVO", basuraPorDia: 0.3 },
  { distrito: "CHILCAYMARCA", basuraPorDia: 0.3 },
  { distrito: "SANTA BARBARA DE CARHUACAYA", basuraPorDia: 0.3 },
  { distrito: "SAN MIGUEL DE ACOS", basuraPorDia: 0.3 },
  { distrito: "TICACO", basuraPorDia: 0.3 },
  { distrito: "QUICHUAS   ", basuraPorDia: 0.3 },
  { distrito: "SOROCHUCO", basuraPorDia: 0.3 },
  { distrito: "SAN PABLO DE PILLAO   ", basuraPorDia: 0.3 },
  { distrito: "YANAS", basuraPorDia: 0.3 },
  { distrito: "HUANDOVAL", basuraPorDia: 0.3 },
  { distrito: "RONDOS", basuraPorDia: 0.29 },
  { distrito: "CALLAHUANCA", basuraPorDia: 0.29 },
  { distrito: "COSPAN", basuraPorDia: 0.29 },
  { distrito: "YUPAN", basuraPorDia: 0.29 },
  { distrito: "CCARHUAYO", basuraPorDia: 0.29 },
  { distrito: "ALBERTO LEVEAU", basuraPorDia: 0.29 },
  { distrito: "PAUCARBAMBA", basuraPorDia: 0.29 },
  { distrito: "UMARI", basuraPorDia: 0.29 },
  { distrito: "SAN JOSE DEL ALTO", basuraPorDia: 0.29 },
  { distrito: "PROGRESO", basuraPorDia: 0.29 },
  { distrito: "MADRIGAL", basuraPorDia: 0.29 },
  { distrito: "CHUNGUI", basuraPorDia: 0.29 },
  { distrito: "QUICHUAS", basuraPorDia: 0.29 },
  { distrito: "ANAPIA", basuraPorDia: 0.28 },
  { distrito: "CAICAY", basuraPorDia: 0.28 },
  { distrito: "MARCAPATA", basuraPorDia: 0.28 },
  { distrito: "CHUNGUI  ", basuraPorDia: 0.28 },
  { distrito: "RAPAYAN", basuraPorDia: 0.28 },
  { distrito: "UCO", basuraPorDia: 0.28 },
  { distrito: "PALLANCHACRA", basuraPorDia: 0.28 },
  { distrito: "CHARAT", basuraPorDia: 0.28 },
  { distrito: "HUANZA", basuraPorDia: 0.28 },
  { distrito: "LAYO", basuraPorDia: 0.28 },
  { distrito: "ITUATA", basuraPorDia: 0.28 },
  { distrito: "QUISHUAR", basuraPorDia: 0.28 },
  { distrito: "SAN JUAN DE ISCOS", basuraPorDia: 0.28 },
  { distrito: "AURAHUA", basuraPorDia: 0.28 },
  { distrito: "TINTAY", basuraPorDia: 0.28 },
  { distrito: "CHUCUITO", basuraPorDia: 0.28 },
  { distrito: "ITUATA  ", basuraPorDia: 0.28 },
  { distrito: "SICSIBAMBA", basuraPorDia: 0.27 },
  { distrito: "COLCA", basuraPorDia: 0.27 },
  { distrito: "LLACLLIN", basuraPorDia: 0.27 },
  { distrito: "TENIENTE MANUEL CLAVERO ", basuraPorDia: 0.27 },
  { distrito: "SANTO TOMAS", basuraPorDia: 0.27 },
  { distrito: "ALTO TAPICHE", basuraPorDia: 0.27 },
  { distrito: "PARIAHUANCA", basuraPorDia: 0.27 },
  { distrito: "SAN PEDRO DE CACHORA", basuraPorDia: 0.27 },
  { distrito: "ACHOMA", basuraPorDia: 0.27 },
  { distrito: "SAN MIGUEL DE CHACCRAMPA", basuraPorDia: 0.27 },
  { distrito: "PAMPACHIRI", basuraPorDia: 0.27 },
  { distrito: "OCUVIRI", basuraPorDia: 0.27 },
  { distrito: "UMACHIRI", basuraPorDia: 0.27 },
  { distrito: "SONDORILLO", basuraPorDia: 0.27 },
  { distrito: "MASMA", basuraPorDia: 0.27 },
  { distrito: "HUASICANCHA", basuraPorDia: 0.26 },
  { distrito: "HUACHUPAMPA", basuraPorDia: 0.26 },
  { distrito: "CONILA", basuraPorDia: 0.26 },
  { distrito: "CASHAPAMPA", basuraPorDia: 0.26 },
  { distrito: "CURASCO", basuraPorDia: 0.26 },
  { distrito: "CULLHUAS", basuraPorDia: 0.26 },
  { distrito: "SANTO DOMINGO DE LOS OLLERO", basuraPorDia: 0.26 },
  { distrito: "HUACRAPUQUIO", basuraPorDia: 0.26 },
  { distrito: "HUANTAN", basuraPorDia: 0.26 },
  { distrito: "SAN JUAN", basuraPorDia: 0.26 },
  { distrito: "TENIENTE MANUEL CLAVERO", basuraPorDia: 0.26 },
  { distrito: "HUASTA", basuraPorDia: 0.26 },
  { distrito: "SAN JUAN DE CHACÑA", basuraPorDia: 0.26 },
  { distrito: "OCUMAL", basuraPorDia: 0.26 },
  { distrito: "NIEPOS", basuraPorDia: 0.26 },
  { distrito: "CCORCA", basuraPorDia: 0.26 },
  { distrito: "HUANCAPON", basuraPorDia: 0.26 },
  { distrito: "VIÑAC", basuraPorDia: 0.26 },
  { distrito: "CACHACHI", basuraPorDia: 0.26 },
  { distrito: "CALLAYUC", basuraPorDia: 0.26 },
  { distrito: "SINA", basuraPorDia: 0.26 },
  { distrito: "RICRAN", basuraPorDia: 0.26 },
  { distrito: "VISTA ALEGRE", basuraPorDia: 0.26 },
  { distrito: "MARCAS", basuraPorDia: 0.25 },
  { distrito: "KELLUYO", basuraPorDia: 0.25 },
  { distrito: "TORRES CAUSANA", basuraPorDia: 0.25 },
  { distrito: "CALAMARCA", basuraPorDia: 0.25 },
  { distrito: "TAPICHE", basuraPorDia: 0.25 },
  { distrito: "TORRES CAUSANA ", basuraPorDia: 0.25 },
  { distrito: "SIBAYO", basuraPorDia: 0.25 },
  { distrito: "COCHAMAL", basuraPorDia: 0.25 },
  { distrito: "SANTO DOMINGO DE LOS OLLEROS", basuraPorDia: 0.25 },
  { distrito: "HUANCA", basuraPorDia: 0.25 },
  { distrito: "CHOCHOPE", basuraPorDia: 0.25 },
  { distrito: "ICHOCAN", basuraPorDia: 0.25 },
  { distrito: "NINABAMBA", basuraPorDia: 0.25 },
  { distrito: "SUMBILCA", basuraPorDia: 0.25 },
  { distrito: "POMACOCHA", basuraPorDia: 0.25 },
  { distrito: "PION", basuraPorDia: 0.25 },
  { distrito: "SAN JUAN DE TANTARANCHE", basuraPorDia: 0.25 },
  { distrito: "YAMON", basuraPorDia: 0.25 },
  { distrito: "ICHUPAMPA", basuraPorDia: 0.25 },
  { distrito: "COAYLLO", basuraPorDia: 0.25 },
  { distrito: "SAN CARLOS", basuraPorDia: 0.24 },
  { distrito: "COPANI", basuraPorDia: 0.24 },
  { distrito: "LA RAMADA", basuraPorDia: 0.24 },
  { distrito: "ANDAGUA", basuraPorDia: 0.24 },
  { distrito: "TICLACAYAN", basuraPorDia: 0.24 },
  { distrito: "QUIVILLA", basuraPorDia: 0.24 },
  { distrito: "SANTIAGO DE TUCUMA  ", basuraPorDia: 0.24 },
  { distrito: "MOSOC LLACTA", basuraPorDia: 0.24 },
  { distrito: "SAN PEDRO DE PILLAO", basuraPorDia: 0.24 },
  { distrito: "YANAQUIHUA", basuraPorDia: 0.24 },
  { distrito: "CHACHAS", basuraPorDia: 0.24 },
  { distrito: "SAN PEDRO DE LARAOS", basuraPorDia: 0.24 },
  { distrito: "LARAMARCA", basuraPorDia: 0.24 },
  { distrito: "SANTA BARBARA DE CARHUACAYAN", basuraPorDia: 0.24 },
  { distrito: "MOLINOPAMPA", basuraPorDia: 0.24 },
  { distrito: "AYAVIRI", basuraPorDia: 0.24 },
  { distrito: "TIRAPATA", basuraPorDia: 0.24 },
  { distrito: "CORONEL CASTAÑEDA", basuraPorDia: 0.24 },
  { distrito: "TAUCA", basuraPorDia: 0.24 },
  { distrito: "SARTIMBAMBA", basuraPorDia: 0.24 },
  { distrito: "VILQUE", basuraPorDia: 0.24 },
  { distrito: "SAN FRANCISCO DE ASIS", basuraPorDia: 0.24 },
  { distrito: "SANTA CRUZ DE CHUCA", basuraPorDia: 0.24 },
  { distrito: "SECCLLA", basuraPorDia: 0.24 },
  { distrito: "YANACA", basuraPorDia: 0.24 },
  { distrito: "LA FLORIDA", basuraPorDia: 0.24 },
  { distrito: "CAPACHICA", basuraPorDia: 0.24 },
  { distrito: "TONGOD", basuraPorDia: 0.24 },
  { distrito: "POCOHUANCA", basuraPorDia: 0.23 },
  { distrito: "ACCOMARCA", basuraPorDia: 0.23 },
  { distrito: "MAMARA", basuraPorDia: 0.23 },
  { distrito: "HUAMBALPA", basuraPorDia: 0.23 },
  { distrito: "SHUNTE", basuraPorDia: 0.23 },
  { distrito: "HUANCARAY", basuraPorDia: 0.23 },
  { distrito: "COCHAS", basuraPorDia: 0.23 },
  { distrito: "SAN JUAN DE TARUCANI", basuraPorDia: 0.23 },
  { distrito: "MEGANTONI   ", basuraPorDia: 0.23 },
  { distrito: "ÑAHUIMPUQUIO", basuraPorDia: 0.23 },
  { distrito: "SAN BENITO", basuraPorDia: 0.23 },
  { distrito: "CONAYCA", basuraPorDia: 0.23 },
  { distrito: "LARAOS", basuraPorDia: 0.23 },
  { distrito: "SURCUBAMBA", basuraPorDia: 0.23 },
  { distrito: "ULCUMAYO", basuraPorDia: 0.23 },
  { distrito: "ACOPAMPA", basuraPorDia: 0.23 },
  { distrito: "HUAMANTANGA", basuraPorDia: 0.23 },
  { distrito: "PIMPINGOS", basuraPorDia: 0.23 },
  { distrito: "BOLIVAR", basuraPorDia: 0.23 },
  { distrito: "PIAS", basuraPorDia: 0.23 },
  { distrito: "PINRA", basuraPorDia: 0.23 },
  { distrito: "QUEROPALCA", basuraPorDia: 0.23 },
  { distrito: "CHUPA", basuraPorDia: 0.22 },
  { distrito: "SANTIAGO DE TUCUMA", basuraPorDia: 0.22 },
  { distrito: "IZCUCHACA", basuraPorDia: 0.22 },
  { distrito: "TICLLOS", basuraPorDia: 0.22 },
  { distrito: "ALCAMENCA", basuraPorDia: 0.22 },
  { distrito: "LIMABAMBA", basuraPorDia: 0.22 },
  { distrito: "MARCAPOMACOCHA", basuraPorDia: 0.22 },
  { distrito: "SAÑAYCA", basuraPorDia: 0.22 },
  { distrito: "HUAMANQUIQUIA", basuraPorDia: 0.22 },
  { distrito: "EL ORO", basuraPorDia: 0.22 },
  { distrito: "MANAS", basuraPorDia: 0.22 },
  { distrito: "MARMOT ", basuraPorDia: 0.22 },
  { distrito: "TUTI", basuraPorDia: 0.22 },
  { distrito: "MEGANTONI", basuraPorDia: 0.22 },
  { distrito: "VILLA KINTIARINA  ", basuraPorDia: 0.22 },
  { distrito: "ATAVILLOS ALTO", basuraPorDia: 0.22 },
  { distrito: "MITO", basuraPorDia: 0.21 },
  { distrito: "CONCHAN", basuraPorDia: 0.21 },
  { distrito: "HUARIBAMBA   ", basuraPorDia: 0.21 },
  { distrito: "CARHUANCA", basuraPorDia: 0.21 },
  { distrito: "CHECRAS", basuraPorDia: 0.21 },
  { distrito: "TUMAY HUARACA", basuraPorDia: 0.21 },
  { distrito: "COTAPARACO", basuraPorDia: 0.21 },
  { distrito: "QUICHES", basuraPorDia: 0.21 },
  { distrito: "SANTA LEONOR", basuraPorDia: 0.21 },
  { distrito: "TINICACHI", basuraPorDia: 0.21 },
  { distrito: "HUAC-HUAS", basuraPorDia: 0.21 },
  { distrito: "VILLA KINTIARINA", basuraPorDia: 0.21 },
  { distrito: "MARMOT", basuraPorDia: 0.21 },
  { distrito: "GREGORIO PITA", basuraPorDia: 0.21 },
  { distrito: "YAURISQUE", basuraPorDia: 0.21 },
  { distrito: "PUTINZA", basuraPorDia: 0.21 },
  { distrito: "HUANIPACA", basuraPorDia: 0.21 },
  { distrito: "CALAPUJA", basuraPorDia: 0.21 },
  { distrito: "LEONCIO PRADO", basuraPorDia: 0.2 },
  { distrito: "OTOCA", basuraPorDia: 0.2 },
  { distrito: "YURACMARCA", basuraPorDia: 0.2 },
  { distrito: "LANGA", basuraPorDia: 0.2 },
  { distrito: "AYAHUANCO   ", basuraPorDia: 0.2 },
  { distrito: "CAHUAC", basuraPorDia: 0.2 },
  { distrito: "SAISA", basuraPorDia: 0.2 },
  { distrito: "KAQUIABAMBA", basuraPorDia: 0.2 },
  { distrito: "SAN JUAN DE CUTERVO", basuraPorDia: 0.2 },
  { distrito: "ANDAYMARCA  ", basuraPorDia: 0.2 },
  { distrito: "HUARIBAMBA", basuraPorDia: 0.2 },
  { distrito: "JOSE MANUEL QUIROZ", basuraPorDia: 0.2 },
  { distrito: "NICASIO", basuraPorDia: 0.2 },
  { distrito: "CHUQUIBAMBA", basuraPorDia: 0.2 },
  { distrito: "CAMILACA", basuraPorDia: 0.2 },
  { distrito: "SAN JUAN DE SIGUAS", basuraPorDia: 0.2 },
  { distrito: "LA PAMPA", basuraPorDia: 0.2 },
  { distrito: "CHETO", basuraPorDia: 0.2 },
  { distrito: "CHICHAS", basuraPorDia: 0.2 },
  { distrito: "CALLANMARCA", basuraPorDia: 0.2 },
  { distrito: "CASITAS", basuraPorDia: 0.2 },
  { distrito: "PARARIN", basuraPorDia: 0.2 },
  { distrito: "AYAHUANCO", basuraPorDia: 0.2 },
  { distrito: "ROBLE   ", basuraPorDia: 0.2 },
  { distrito: "CHIMBAN", basuraPorDia: 0.2 },
  { distrito: "YANACANCHA", basuraPorDia: 0.2 },
  { distrito: "LANCONES", basuraPorDia: 0.2 },
  { distrito: "URPAY", basuraPorDia: 0.19 },
  { distrito: "HUAYANA", basuraPorDia: 0.19 },
  { distrito: "SAN FELIPE", basuraPorDia: 0.19 },
  { distrito: "SANTA CRUZ", basuraPorDia: 0.19 },
  { distrito: "PULAN", basuraPorDia: 0.19 },
  { distrito: "MARIA", basuraPorDia: 0.19 },
  { distrito: "COCHARCAS", basuraPorDia: 0.19 },
  { distrito: "CARHUACALLANGA", basuraPorDia: 0.19 },
  { distrito: "LLAUTA", basuraPorDia: 0.19 },
  { distrito: "CAJAY", basuraPorDia: 0.19 },
  { distrito: "CUISPES", basuraPorDia: 0.19 },
  { distrito: "HUAYLLAN", basuraPorDia: 0.19 },
  { distrito: "AYAUCA", basuraPorDia: 0.19 },
  { distrito: "PAMPAS CHICO", basuraPorDia: 0.19 },
  { distrito: "MONTEVIDEO", basuraPorDia: 0.19 },
  { distrito: "SANTA CATALINA", basuraPorDia: 0.19 },
  { distrito: "SAN PEDRO DE LARCAY", basuraPorDia: 0.19 },
  { distrito: "PAICO", basuraPorDia: 0.19 },
  { distrito: "YUNGA", basuraPorDia: 0.19 },
  { distrito: "PILPICHACA", basuraPorDia: 0.19 },
  { distrito: "HUANCAYA", basuraPorDia: 0.19 },
  { distrito: "ANDAYMARCA", basuraPorDia: 0.19 },
  { distrito: "SAN LUIS DE LUCMA", basuraPorDia: 0.18 },
  { distrito: "POMACANCHA", basuraPorDia: 0.18 },
  { distrito: "SAN ANTONIO DE CHUCA", basuraPorDia: 0.18 },
  { distrito: "COCHABAMBA", basuraPorDia: 0.18 },
  { distrito: "HUANTAR", basuraPorDia: 0.18 },
  { distrito: "SANTO TOMAS DE PATA", basuraPorDia: 0.18 },
  { distrito: "LUYA VIEJO", basuraPorDia: 0.18 },
  { distrito: "CHINGALPO", basuraPorDia: 0.18 },
  { distrito: "PATAMBUCO", basuraPorDia: 0.18 },
  { distrito: "PUCACOLPA", basuraPorDia: 0.18 },
  { distrito: "PEDRO VILCA APAZA", basuraPorDia: 0.18 },
  { distrito: "PAMPAMARCA", basuraPorDia: 0.18 },
  { distrito: "PAMPAROMAS", basuraPorDia: 0.18 },
  { distrito: "SAN GREGORIO", basuraPorDia: 0.18 },
  { distrito: "MARIA PARADO DE BELLIDO", basuraPorDia: 0.18 },
  { distrito: "HUAÑEC", basuraPorDia: 0.18 },
  { distrito: "ROBLE", basuraPorDia: 0.18 },
  { distrito: "CORTEGANA", basuraPorDia: 0.18 },
  { distrito: "ROSASPATA", basuraPorDia: 0.18 },
  { distrito: "TUPAC AMARU", basuraPorDia: 0.18 },
  { distrito: "LEVANTO", basuraPorDia: 0.18 },
  { distrito: "SARA SARA", basuraPorDia: 0.18 },
  { distrito: "PUCACOLPA  ", basuraPorDia: 0.18 },
  { distrito: "CARAMPOMA", basuraPorDia: 0.18 },
  { distrito: "LLUTA", basuraPorDia: 0.18 },
  { distrito: "SUITUCANCHA", basuraPorDia: 0.18 },
  { distrito: "ANTIOQUIA", basuraPorDia: 0.18 },
  { distrito: "LARI", basuraPorDia: 0.18 },
  { distrito: "CONDOROMA", basuraPorDia: 0.17 },
  { distrito: "CHARCANA", basuraPorDia: 0.17 },
  { distrito: "ATAQUERO", basuraPorDia: 0.17 },
  { distrito: "HUAYLLAY GRANDE", basuraPorDia: 0.17 },
  { distrito: "SANAGORAN", basuraPorDia: 0.17 },
  { distrito: "CHACCHO", basuraPorDia: 0.17 },
  { distrito: "AMBAR", basuraPorDia: 0.17 },
  { distrito: "CAYARANI", basuraPorDia: 0.17 },
  { distrito: "PICHIRHUA", basuraPorDia: 0.17 },
  { distrito: "SANTIAGO DE ANCHUCAYA", basuraPorDia: 0.17 },
  { distrito: "SANTIAGO DE CHILCAS", basuraPorDia: 0.17 },
  { distrito: "IRAY", basuraPorDia: 0.17 },
  { distrito: "SAN FRANCISCO DE CAYRAN ", basuraPorDia: 0.17 },
  { distrito: "HUAYAN", basuraPorDia: 0.17 },
  { distrito: "TINTAY PUNCU", basuraPorDia: 0.17 },
  { distrito: "CHORAS", basuraPorDia: 0.17 },
  { distrito: "PACOBAMBA", basuraPorDia: 0.17 },
  { distrito: "CURICACA", basuraPorDia: 0.17 },
  { distrito: "HUAYLLAHUARA", basuraPorDia: 0.17 },
  { distrito: "CURPAHUASI", basuraPorDia: 0.17 },
  { distrito: "APONGO", basuraPorDia: 0.17 },
  { distrito: "SAN ANTONIO DE CHUCA ", basuraPorDia: 0.17 },
  { distrito: "COLONIA", basuraPorDia: 0.17 },
  { distrito: "CHUGUR", basuraPorDia: 0.17 },
  { distrito: "BAMBAS", basuraPorDia: 0.17 },
  { distrito: "COCABAMBA", basuraPorDia: 0.17 },
  { distrito: "TORAYA", basuraPorDia: 0.16 },
  { distrito: "PATAYPAMPA", basuraPorDia: 0.16 },
  { distrito: "HUAYLILLAS", basuraPorDia: 0.16 },
  { distrito: "HUANGASCAR", basuraPorDia: 0.16 },
  { distrito: "HONGOS", basuraPorDia: 0.16 },
  { distrito: "SITAJARA", basuraPorDia: 0.16 },
  { distrito: "SAN BUENAVENTURA", basuraPorDia: 0.16 },
  { distrito: "CAÑARIS", basuraPorDia: 0.16 },
  { distrito: "ATAVILLOS BAJO", basuraPorDia: 0.16 },
  { distrito: "VILAVILA", basuraPorDia: 0.16 },
  { distrito: "CARHUAPAMPA", basuraPorDia: 0.16 },
  { distrito: "MICAELA BASTIDAS", basuraPorDia: 0.16 },
  { distrito: "SANTIAGO DE TUNA", basuraPorDia: 0.16 },
  { distrito: "SAN ISIDRO DE MAINO", basuraPorDia: 0.16 },
  { distrito: "SAN FRANCISCO DEL YESO", basuraPorDia: 0.16 },
  { distrito: "SAN PEDRO DE CHAULAN   ", basuraPorDia: 0.16 },
  { distrito: "SHUNQUI", basuraPorDia: 0.16 },
  { distrito: "SILLAPATA", basuraPorDia: 0.16 },
  { distrito: "TAURIPAMPA", basuraPorDia: 0.16 },
  { distrito: "SAN MIGUEL DE ACO", basuraPorDia: 0.16 },
  { distrito: "PAMPA HERMOSA", basuraPorDia: 0.16 },
  { distrito: "PISUQUIA", basuraPorDia: 0.16 },
  { distrito: "CHOROS", basuraPorDia: 0.15 },
  { distrito: "CUJILLO", basuraPorDia: 0.15 },
  { distrito: "GORGOR", basuraPorDia: 0.15 },
  { distrito: "NANCHOC", basuraPorDia: 0.15 },
  { distrito: "ANGUIA", basuraPorDia: 0.15 },
  { distrito: "SANTA CRUZ DE ANDAMARCA", basuraPorDia: 0.15 },
  { distrito: "PICHIGUA", basuraPorDia: 0.15 },
  { distrito: "CONDORMARCA", basuraPorDia: 0.15 },
  { distrito: "SAN ISIDRO", basuraPorDia: 0.15 },
  { distrito: "PATIBAMBA", basuraPorDia: 0.15 },
  { distrito: "SAMAN", basuraPorDia: 0.15 },
  { distrito: "LLUMPA", basuraPorDia: 0.15 },
  { distrito: "OMAS", basuraPorDia: 0.15 },
  { distrito: "CORIS", basuraPorDia: 0.15 },
  { distrito: "QUINCHES", basuraPorDia: 0.15 },
  { distrito: "SAN PEDRO DE PALCO", basuraPorDia: 0.15 },
  { distrito: "MALVAS", basuraPorDia: 0.15 },
  { distrito: "SAN PEDRO DE CHAULAN", basuraPorDia: 0.15 },
  { distrito: "CHURUJA", basuraPorDia: 0.15 },
  { distrito: "CHANCAY", basuraPorDia: 0.15 },
  { distrito: "SAN ANTONIO DE ANTAPARCO", basuraPorDia: 0.15 },
  { distrito: "TANTARA", basuraPorDia: 0.15 },
  { distrito: "CHIARA", basuraPorDia: 0.15 },
  { distrito: "PAUCARCOLLA", basuraPorDia: 0.15 },
  { distrito: "OXAMARCA", basuraPorDia: 0.15 },
  { distrito: "CHACAPAMPA", basuraPorDia: 0.15 },
  { distrito: "JOSE GALVEZ", basuraPorDia: 0.15 },
  { distrito: "QUINOCAY", basuraPorDia: 0.15 },
  { distrito: "QUISQUI    ", basuraPorDia: 0.15 },
  { distrito: "SAN MIGUEL DE CORPANQUI", basuraPorDia: 0.15 },
  { distrito: "COLPAS", basuraPorDia: 0.15 },
  { distrito: "BOLOGNESI", basuraPorDia: 0.14 },
  { distrito: "LANGUI", basuraPorDia: 0.14 },
  { distrito: "QUIACA", basuraPorDia: 0.14 },
  { distrito: "PUEBLO LIBRE", basuraPorDia: 0.14 },
  { distrito: "POLOBAYA", basuraPorDia: 0.14 },
  { distrito: "VIRUNDO", basuraPorDia: 0.14 },
  { distrito: "QUILCA", basuraPorDia: 0.14 },
  { distrito: "QUEHUE", basuraPorDia: 0.14 },
  { distrito: "CIRCA", basuraPorDia: 0.14 },
  { distrito: "ROSA PANDURO", basuraPorDia: 0.14 },
  { distrito: "SAN FRANCISCO DE SANGAYAICO", basuraPorDia: 0.14 },
  { distrito: "LONYA CHICO", basuraPorDia: 0.14 },
  { distrito: "ROSA PANDURO ", basuraPorDia: 0.14 },
  { distrito: "SAN PEDRO DE HUACARPANA", basuraPorDia: 0.14 },
  { distrito: "VILCABAMBA    ", basuraPorDia: 0.14 },
  { distrito: "HUANUARA", basuraPorDia: 0.14 },
  { distrito: "HUAYLLACAYAN", basuraPorDia: 0.14 },
  { distrito: "RAGASH", basuraPorDia: 0.14 },
  { distrito: "SAN ANDRES DE TUPICOCHA", basuraPorDia: 0.14 },
  { distrito: "TORIBIO CASANOVA", basuraPorDia: 0.14 },
  { distrito: "SANTO DOMINGO DE ANDA   ", basuraPorDia: 0.14 },
  { distrito: "CASCA", basuraPorDia: 0.14 },
  { distrito: "HUAYLLATI", basuraPorDia: 0.14 },
  { distrito: "CHANCAYBAÑOS", basuraPorDia: 0.14 },
  { distrito: "LUCRE", basuraPorDia: 0.13 },
  { distrito: "UCHURACCAY", basuraPorDia: 0.13 },
  { distrito: "INGUILPATA", basuraPorDia: 0.13 },
  { distrito: "HERMILIO VALDIZAN", basuraPorDia: 0.13 },
  { distrito: "TOMEPAMPA", basuraPorDia: 0.13 },
  { distrito: "JILILI", basuraPorDia: 0.13 },
  { distrito: "ACAS", basuraPorDia: 0.13 },
  { distrito: "CHETILLA", basuraPorDia: 0.13 },
  { distrito: "SAN FRANCISCO", basuraPorDia: 0.13 },
  { distrito: "JACAS CHICO", basuraPorDia: 0.13 },
  { distrito: "COVIRIALI", basuraPorDia: 0.13 },
  { distrito: "EL CARMEN DE LA FRONTERA", basuraPorDia: 0.13 },
  { distrito: "COALAQUE", basuraPorDia: 0.13 },
  { distrito: "ANTONIO RAYMONDI", basuraPorDia: 0.13 },
  { distrito: "HUAYO", basuraPorDia: 0.13 },
  { distrito: "ANDAJES", basuraPorDia: 0.13 },
  { distrito: "COCHAMARCA", basuraPorDia: 0.13 },
  { distrito: "ANDAMARCA", basuraPorDia: 0.13 },
  { distrito: "MUSGA", basuraPorDia: 0.13 },
  { distrito: "MANGAS", basuraPorDia: 0.13 },
  { distrito: "SANTO DOMINGO DE ACOBAMBA", basuraPorDia: 0.13 },
  { distrito: "SANTO DOMINGO DE ANDA", basuraPorDia: 0.13 },
  { distrito: "MACATE", basuraPorDia: 0.13 },
  { distrito: "HUAYACUNDO ARMA", basuraPorDia: 0.13 },
  { distrito: "TAMBILLO", basuraPorDia: 0.13 },
  { distrito: "BALSAS", basuraPorDia: 0.13 },
  { distrito: "NUEVO OCCORO", basuraPorDia: 0.13 },
  { distrito: "CORCULLA", basuraPorDia: 0.13 },
  { distrito: "SAN CRISTOBAL DE RAJAN", basuraPorDia: 0.13 },
  { distrito: "AYAVI", basuraPorDia: 0.13 },
  { distrito: "PILCHACA", basuraPorDia: 0.13 },
  { distrito: "CHICCHE", basuraPorDia: 0.13 },
  { distrito: "MIGUEL IGLESIAS", basuraPorDia: 0.13 },
  { distrito: "QUISQUI", basuraPorDia: 0.13 },
  { distrito: "MONOBAMBA", basuraPorDia: 0.13 },
  { distrito: "UCHURACCAY   ", basuraPorDia: 0.13 },
  { distrito: "HERMILIO VALDIZAN   ", basuraPorDia: 0.13 },
  { distrito: "ARANCAY", basuraPorDia: 0.13 },
  { distrito: "JIVIA", basuraPorDia: 0.12 },
  { distrito: "CAJAMARQUILLA", basuraPorDia: 0.12 },
  { distrito: "ONDORES", basuraPorDia: 0.12 },
  { distrito: "SAN JUAN DE YANAC", basuraPorDia: 0.12 },
  { distrito: "PANCAN", basuraPorDia: 0.12 },
  { distrito: "SOPLIN   ", basuraPorDia: 0.12 },
  { distrito: "TAPACOCHA", basuraPorDia: 0.12 },
  { distrito: "ONGOY", basuraPorDia: 0.12 },
  { distrito: "PALCA", basuraPorDia: 0.12 },
  { distrito: "QUILAHUANI", basuraPorDia: 0.12 },
  { distrito: "LARIA", basuraPorDia: 0.12 },
  { distrito: "LACABAMBA", basuraPorDia: 0.12 },
  { distrito: "ARMA", basuraPorDia: 0.12 },
  { distrito: "TUPE", basuraPorDia: 0.12 },
  { distrito: "SOPLIN", basuraPorDia: 0.12 },
  { distrito: "CHIGUIRIP", basuraPorDia: 0.12 },
  { distrito: "LAMPIAN", basuraPorDia: 0.12 },
  { distrito: "SUCCHA", basuraPorDia: 0.12 },
  { distrito: "ARAHUAY", basuraPorDia: 0.12 },
  { distrito: "UNICACHI", basuraPorDia: 0.12 },
  { distrito: "CHILCAYOC", basuraPorDia: 0.12 },
  { distrito: "ABELARDO PARDO LEZAMETA", basuraPorDia: 0.12 },
  { distrito: "MILPUC", basuraPorDia: 0.12 },
  { distrito: "PLATERIA", basuraPorDia: 0.12 },
  { distrito: "COLTA", basuraPorDia: 0.12 },
  { distrito: "CHOROPAMPA", basuraPorDia: 0.12 },
  { distrito: "ALTO PICHIGUA", basuraPorDia: 0.12 },
  { distrito: "GUZMANGO", basuraPorDia: 0.11 },
  { distrito: "VITOC", basuraPorDia: 0.11 },
  { distrito: "LOS CHANKAS  ", basuraPorDia: 0.11 },
  { distrito: "PROVIDENCIA", basuraPorDia: 0.11 },
  { distrito: "ONGOY     ", basuraPorDia: 0.11 },
  { distrito: "TIBILLO", basuraPorDia: 0.11 },
  { distrito: "ACOBAMBILLA", basuraPorDia: 0.11 },
  { distrito: "HUANCHAY", basuraPorDia: 0.11 },
  { distrito: "LA LIBERTAD", basuraPorDia: 0.11 },
  { distrito: "SAN CRISTOBAL", basuraPorDia: 0.11 },
  { distrito: "YAGUAS ", basuraPorDia: 0.11 },
  { distrito: "LAMBRAS", basuraPorDia: 0.11 },
  { distrito: "GAMARRA", basuraPorDia: 0.11 },
  { distrito: "LA PRIMAVERA", basuraPorDia: 0.11 },
  { distrito: "CANIS", basuraPorDia: 0.11 },
  { distrito: "EL PRADO", basuraPorDia: 0.11 },
  { distrito: "LOS CHANKAS", basuraPorDia: 0.11 },
  { distrito: "PACAPAUSA", basuraPorDia: 0.11 },
  { distrito: "CUPI", basuraPorDia: 0.11 },
  { distrito: "LLOQUE", basuraPorDia: 0.11 },
  { distrito: "HUAYLLAPAMPA", basuraPorDia: 0.11 },
  { distrito: "MARIATANA", basuraPorDia: 0.11 },
  { distrito: "ANDARAY", basuraPorDia: 0.11 },
  { distrito: "CHOCO", basuraPorDia: 0.11 },
  { distrito: "HUACAÑA", basuraPorDia: 0.11 },
  { distrito: "BELEN", basuraPorDia: 0.11 },
  { distrito: "QUINISTAQUILLAS", basuraPorDia: 0.11 },
  { distrito: "LAHUAYTAMBO", basuraPorDia: 0.11 },
  { distrito: "CHINCHIHUASI", basuraPorDia: 0.11 },
  { distrito: "YAGUAS", basuraPorDia: 0.11 },
  { distrito: "HUAYLAS", basuraPorDia: 0.11 },
  { distrito: "BAÑOS", basuraPorDia: 0.11 },
  { distrito: "POCSI", basuraPorDia: 0.11 },
  { distrito: "YANAC", basuraPorDia: 0.1 },
  { distrito: "TARUCACHI", basuraPorDia: 0.1 },
  { distrito: "CONCEPCION", basuraPorDia: 0.1 },
  { distrito: "CHOJATA", basuraPorDia: 0.1 },
  { distrito: "MOYA", basuraPorDia: 0.1 },
  { distrito: "MORCOLLA", basuraPorDia: 0.1 },
  { distrito: "SAURAMA", basuraPorDia: 0.1 },
  { distrito: "SAN SALVADOR DE QUIJE", basuraPorDia: 0.1 },
  { distrito: "TOCMOCHE", basuraPorDia: 0.1 },
  { distrito: "VEINTISIETE DE NOVIEMBRE", basuraPorDia: 0.1 },
  { distrito: "ALIS", basuraPorDia: 0.1 },
  { distrito: "CHUPAMARCA", basuraPorDia: 0.1 },
  { distrito: "YARUMAYO", basuraPorDia: 0.1 },
  { distrito: "MOLLEPAMPA", basuraPorDia: 0.1 },
  { distrito: "NAVAN", basuraPorDia: 0.1 },
  { distrito: "CHOCOS", basuraPorDia: 0.1 },
  { distrito: "UCUNCHA", basuraPorDia: 0.1 },
  { distrito: "SANTO TORIBIO", basuraPorDia: 0.1 },
  { distrito: "SAN MARCOS DE ROCCHAC", basuraPorDia: 0.1 },
  { distrito: "CHECCA", basuraPorDia: 0.1 },
  { distrito: "COCHAPETI", basuraPorDia: 0.1 },
  { distrito: "ANDABAMBA", basuraPorDia: 0.1 },
  { distrito: "SALCABAMBA", basuraPorDia: 0.1 },
  { distrito: "LA YARADA LOS PALOS  ", basuraPorDia: 0.1 },
  { distrito: "CHACAPALPA", basuraPorDia: 0.1 },
  { distrito: "SALCAHUASI", basuraPorDia: 0.1 },
  { distrito: "SAN MIGUEL DE MAYOCC", basuraPorDia: 0.09 },
  { distrito: "CHAVIN", basuraPorDia: 0.09 },
  { distrito: "SEXI", basuraPorDia: 0.09 },
  { distrito: "QUINUABAMBA", basuraPorDia: 0.09 },
  { distrito: "LA MERCED", basuraPorDia: 0.09 },
  { distrito: "TOMAS", basuraPorDia: 0.09 },
  { distrito: "CHILCAS", basuraPorDia: 0.09 },
  { distrito: "YANAMA", basuraPorDia: 0.09 },
  { distrito: "SAN ANTONIO", basuraPorDia: 0.09 },
  { distrito: "CAPAYA", basuraPorDia: 0.09 },
  { distrito: "CORDOVA", basuraPorDia: 0.09 },
  { distrito: "SAN FRANCISCO DE CAYRAN", basuraPorDia: 0.09 },
  { distrito: "JUSTO APU SAHUARAURA", basuraPorDia: 0.09 },
  { distrito: "LA YARADA LOS PALOS", basuraPorDia: 0.09 },
  { distrito: "SALAMANCA", basuraPorDia: 0.09 },
  { distrito: "SOLOCO", basuraPorDia: 0.09 },
  { distrito: "CHALCOS", basuraPorDia: 0.09 },
  { distrito: "SAN FRANCISCO DE RAVACAYCO", basuraPorDia: 0.09 },
  { distrito: "MARCABAL", basuraPorDia: 0.09 },
  { distrito: "LLIPA", basuraPorDia: 0.09 },
  { distrito: "SAN FRANCISCO DE DAGUAS", basuraPorDia: 0.09 },
  { distrito: "MARCABAMBA", basuraPorDia: 0.09 },
  { distrito: "TORO", basuraPorDia: 0.09 },
  { distrito: "PARARCA", basuraPorDia: 0.09 },
  { distrito: "TAPAIRIHUA", basuraPorDia: 0.09 },
  { distrito: "SAN BERNARDINO", basuraPorDia: 0.09 },
  { distrito: "CUENCA", basuraPorDia: 0.09 },
  { distrito: "ESTIQUE-PAMPA", basuraPorDia: 0.09 },
  { distrito: "CACRA", basuraPorDia: 0.09 },
  { distrito: "ESTIQUE", basuraPorDia: 0.09 },
  { distrito: "AMANTANI", basuraPorDia: 0.09 },
  { distrito: "CANCHABAMBA", basuraPorDia: 0.09 },
  { distrito: "TIQUILLACA", basuraPorDia: 0.09 },
  { distrito: "MACHAGUAY", basuraPorDia: 0.09 },
  { distrito: "ACOCHACA", basuraPorDia: 0.09 },
  { distrito: "GRANADA", basuraPorDia: 0.09 },
  { distrito: "PACHAMARCA", basuraPorDia: 0.08 },
  { distrito: "CAUJUL", basuraPorDia: 0.08 },
  { distrito: "SANTIAGO DE CHOCORVOS", basuraPorDia: 0.08 },
  { distrito: "HUATA", basuraPorDia: 0.08 },
  { distrito: "SAN PEDRO", basuraPorDia: 0.08 },
  { distrito: "SAN JERONIMO", basuraPorDia: 0.08 },
  { distrito: "HUACASCHUQUE", basuraPorDia: 0.08 },
  { distrito: "SANTIAGO DE QUIRAHUARA", basuraPorDia: 0.08 },
  { distrito: "SAN JOSE DE USHUA", basuraPorDia: 0.08 },
  { distrito: "TUMBADEN", basuraPorDia: 0.08 },
  { distrito: "ACO", basuraPorDia: 0.08 },
  { distrito: "FITZCARRALD   ", basuraPorDia: 0.08 },
  { distrito: "CUPISNIQUE", basuraPorDia: 0.08 },
  { distrito: "SAN PEDRO DE PILAS", basuraPorDia: 0.08 },
  { distrito: "CATILLUC", basuraPorDia: 0.08 },
  { distrito: "LUIS CARRANZA", basuraPorDia: 0.08 },
  { distrito: "LA ESPERANZA", basuraPorDia: 0.08 },
  { distrito: "SUYCKUTAMBO", basuraPorDia: 0.08 },
  { distrito: "OCORURO", basuraPorDia: 0.08 },
  { distrito: "SANTA ROSA", basuraPorDia: 0.08 },
  { distrito: "SAN PEDRO DE HUANCAYRE", basuraPorDia: 0.08 },
  { distrito: "MIRACOSTA", basuraPorDia: 0.08 },
  { distrito: "HUACLLAN", basuraPorDia: 0.08 },
  { distrito: "CURIBAYA", basuraPorDia: 0.08 },
  { distrito: "ORONCOY", basuraPorDia: 0.08 },
  { distrito: "OLLARAYA", basuraPorDia: 0.08 },
  { distrito: "ATUNCOLLA", basuraPorDia: 0.08 },
  { distrito: "MADEAN", basuraPorDia: 0.08 },
  { distrito: "CARANIA", basuraPorDia: 0.08 },
  { distrito: "SAN SILVESTRE DE COCHAN", basuraPorDia: 0.08 },
  { distrito: "PAMPAS GRANDE", basuraPorDia: 0.07 },
  { distrito: "SHUPLUY", basuraPorDia: 0.07 },
  { distrito: "ORONCCOY", basuraPorDia: 0.07 },
  { distrito: "FITZCARRALD", basuraPorDia: 0.07 },
  { distrito: "SAN MATEO DE OTAO", basuraPorDia: 0.07 },
  { distrito: "ASQUIPATA", basuraPorDia: 0.07 },
  { distrito: "CAHUACHO", basuraPorDia: 0.07 },
  { distrito: "AYO", basuraPorDia: 0.07 },
  { distrito: "TANTAMAYO", basuraPorDia: 0.07 },
  { distrito: "OLLEROS", basuraPorDia: 0.07 },
  { distrito: "MANTA", basuraPorDia: 0.07 },
  { distrito: "EL CARMEN", basuraPorDia: 0.07 },
  { distrito: "FIDEL OLIVAS ESCUDERO", basuraPorDia: 0.07 },
  { distrito: "ANRA", basuraPorDia: 0.07 },
  { distrito: "SAN JUAN DE RONTOY", basuraPorDia: 0.07 },
  { distrito: "MASMA CHICCHE", basuraPorDia: 0.07 },
  { distrito: "JORGE CHAVEZ", basuraPorDia: 0.07 },
  { distrito: "HUAMPARA", basuraPorDia: 0.07 },
  { distrito: "CHILIQUIN", basuraPorDia: 0.07 },
  { distrito: "SAUCEPAMPA", basuraPorDia: 0.07 },
  { distrito: "ALFONSO UGARTE", basuraPorDia: 0.07 },
  { distrito: "SORAYA", basuraPorDia: 0.07 },
  { distrito: "TURPAY", basuraPorDia: 0.07 },
  { distrito: "CHACABAMBA", basuraPorDia: 0.07 },
  { distrito: "SAN JOAQUIN", basuraPorDia: 0.07 },
  { distrito: "UPAHUACHO", basuraPorDia: 0.07 },
  { distrito: "ASUNCION", basuraPorDia: 0.07 },
  { distrito: "ORONCOY  ", basuraPorDia: 0.07 },
  { distrito: "JANJAILLO", basuraPorDia: 0.07 },
  { distrito: "SAN JUAN DE LICUPIS", basuraPorDia: 0.07 },
  { distrito: "CHUMUCH", basuraPorDia: 0.07 },
  { distrito: "SAN ANTONIO DE CUSICANCHA", basuraPorDia: 0.06 },
  { distrito: "CASCAPARA", basuraPorDia: 0.06 },
  { distrito: "LLAMA", basuraPorDia: 0.06 },
  { distrito: "MATACOTO", basuraPorDia: 0.06 },
  { distrito: "HEROES ALBARRACIN", basuraPorDia: 0.06 },
  { distrito: "SAN JOSE DE TICLLAS", basuraPorDia: 0.06 },
  { distrito: "ELEAZAR GUZMAN BARRON", basuraPorDia: 0.06 },
  { distrito: "SANGALLAYA", basuraPorDia: 0.06 },
  { distrito: "IHUAYLLO", basuraPorDia: 0.06 },
  { distrito: "CHISQUILLA", basuraPorDia: 0.06 },
  { distrito: "SANTO DOMINGO DE CAPILLAS", basuraPorDia: 0.06 },
  { distrito: "LONGUITA", basuraPorDia: 0.06 },
  { distrito: "PAMPAS", basuraPorDia: 0.06 },
  { distrito: "HUACHOS", basuraPorDia: 0.06 },
  { distrito: "SAYLA", basuraPorDia: 0.06 },
  { distrito: "UTICYACU", basuraPorDia: 0.06 },
  { distrito: "HUAMATAMBO", basuraPorDia: 0.06 },
  { distrito: "VITIS", basuraPorDia: 0.05 },
  { distrito: "CAMINACA  ", basuraPorDia: 0.05 },
  { distrito: "AZANGARO", basuraPorDia: 0.05 },
  { distrito: "UÑON", basuraPorDia: 0.05 },
  { distrito: "PARIAHUANCA   ", basuraPorDia: 0.05 },
  { distrito: "SANTA CRUZ DE TOLED", basuraPorDia: 0.05 },
  { distrito: "TIPAN", basuraPorDia: 0.05 },
  { distrito: "ATIQUIPA", basuraPorDia: 0.05 },
  { distrito: "PARANDAY", basuraPorDia: 0.05 },
  { distrito: "ONGON", basuraPorDia: 0.05 },
  { distrito: "VALERA", basuraPorDia: 0.05 },
  { distrito: "LUCMA", basuraPorDia: 0.05 },
  { distrito: "SANTIAGO DE PUPUJA", basuraPorDia: 0.05 },
  { distrito: "SAN JUAN DE SALINAS", basuraPorDia: 0.05 },
  { distrito: "VILCA", basuraPorDia: 0.05 },
  { distrito: "YAUCA DEL ROSARIO", basuraPorDia: 0.05 },
  { distrito: "COCAS", basuraPorDia: 0.05 },
  { distrito: "SONCHE", basuraPorDia: 0.05 },
  { distrito: "QUITO-ARMA", basuraPorDia: 0.05 },
  { distrito: "MATALAQUE", basuraPorDia: 0.05 },
  { distrito: "OCOYO", basuraPorDia: 0.04 },
  { distrito: "LINCHA", basuraPorDia: 0.04 },
  { distrito: "HUANUHUANU", basuraPorDia: 0.04 },
  { distrito: "LA CUESTA", basuraPorDia: 0.04 },
  { distrito: "JIRCAN", basuraPorDia: 0.04 },
  { distrito: "QUECHUALLA", basuraPorDia: 0.04 },
  { distrito: "INCHUPALLA", basuraPorDia: 0.04 },
  { distrito: "CHIRIMOTO", basuraPorDia: 0.04 },
  { distrito: "TAURIA", basuraPorDia: 0.04 },
  { distrito: "CAPAZO", basuraPorDia: 0.04 },
  { distrito: "COLCABAMBA", basuraPorDia: 0.04 },
  { distrito: "CAMINACA", basuraPorDia: 0.04 },
  { distrito: "HEROINAS TOLEDO", basuraPorDia: 0.04 },
  { distrito: "COROSHA", basuraPorDia: 0.04 },
  { distrito: "SAN JAVIER DE ALPABAMBA", basuraPorDia: 0.04 },
  { distrito: "QUINJALCA", basuraPorDia: 0.04 },
  { distrito: "YAUCA DEL ROSARIO ", basuraPorDia: 0.04 },
  { distrito: "CALQUIS", basuraPorDia: 0.04 },
  { distrito: "CHINCHO", basuraPorDia: 0.03 },
  { distrito: "TAPAY", basuraPorDia: 0.03 },
  { distrito: "PUTIS", basuraPorDia: 0.03 },
  { distrito: "LA CAPILLA", basuraPorDia: 0.03 },
  { distrito: "CAPILLAS", basuraPorDia: 0.03 },
  { distrito: "TOTORA", basuraPorDia: 0.03 },
  { distrito: "SAN JUAN DE LOPECANCHA", basuraPorDia: 0.03 },
  { distrito: "RECTA", basuraPorDia: 0.03 },
  { distrito: "ACHAYA", basuraPorDia: 0.02 },
  { distrito: "UTCO", basuraPorDia: 0.02 },
  { distrito: "SANTA ISABEL DE SIGUAS", basuraPorDia: 0.02 },
];
